<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_tys_clinker04_bjbb.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_tys.zc_nxjc_qtx_tys_clinker04_bjbb" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

        <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_qtx_tys_clinker04";
        publicData.sceneName = "4#包机报表";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_tys/zc_nxjc_qtx_tys_clinker04_bjbb.png');width: 1557px; height: 806px;  overflow: hidden; ">
        <%--标签粘贴处--%>
<%--        <button onclick="CheckTags()">检查标签</button>--%>
        <%--开关量--%>  
        <%--模拟量--%>
        <%--模拟量--%>


        <%--表1第一行--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sp_1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 139px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dbjs_1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 139px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sbdz_1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 139px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dqdz_1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 139px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_1_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 139px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_1_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 139px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_1_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 139px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_1_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 139px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_1_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 139px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_1_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 139px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
         <%--表1第二行--%>   
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sp_2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 170px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dbjs_2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 170px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sbdz_2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 170px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dqdz_2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 170px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_2_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 170px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_2_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 170px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_2_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 170px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_2_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 170px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_2_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 170px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_2_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 170px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <%--表1第三行--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sp_3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 200px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dbjs_3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 200px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sbdz_3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 200px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dqdz_3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 200px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 200px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 200px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 200px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 200px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 200px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 200px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <%--表1第四行--%> 
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sp_4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 230px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dbjs_4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 230px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sbdz_4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 230px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dqdz_4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 230px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 230px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 230px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 230px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 230px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 230px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 230px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
         <%--表1第五行--%> 
         <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sp_5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 259px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dbjs_5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 259px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sbdz_5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 259px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dqdz_5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 259px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_5_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 259px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_5_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 259px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_5_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 259px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_5_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 259px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_5_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 259px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_5_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 259px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
         <%--表1第六行--%> 
         <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sp_6>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 289px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dbjs_6>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 289px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sbdz_6>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 289px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dqdz_6>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 289px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_6_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 289px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_6_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 289px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_6_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 289px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_6_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 289px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_6_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 289px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_6_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 289px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
         <%--表1第七行--%> 
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sp_7>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 319px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dbjs_7>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 319px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sbdz_7>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 319px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dqdz_7>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 319px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_7_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 319px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_7_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 319px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_7_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 319px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_7_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 319px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_7_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 319px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_7_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 319px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <%--表1第八行--%> 
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sp_8>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 349px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dbjs_8>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 349px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.sbdz_8>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 349px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_4.dqdz_8>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 349px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_8_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 349px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_8_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 349px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_8_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 349px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_8_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 349px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_8_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 349px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_8_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 349px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
     <%--表1第九行--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LDPLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 382px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LDCLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 382px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LMPLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 382px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LMCLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 382px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LYPLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 382px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_3_LYCLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 382px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>

      <%--第二个表的模拟量--%>
         <%--表2第一行--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sp_1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 527px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dbjs_1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 527px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sbdz_1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 527px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dqdz_1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 527px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_41_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 527px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_41_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 527px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_41_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 527px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_41_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 527px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_41_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 527px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_41_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 527px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
         <%--表2第二行--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sp_2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 557px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dbjs_2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 557px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sbdz_2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 557px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dqdz_2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 557px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_42_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 557px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_42_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 557px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_42_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 557px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_42_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 557px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_42_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 557px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_42_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 557px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
         <%--表2第三行--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sp_3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 587px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dbjs_3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 587px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sbdz_3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 587px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dqdz_3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 587px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_43_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 587px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_43_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 587px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_43_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 587px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_43_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 587px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_43_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 587px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_43_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 587px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
         <%--表2第四行--%>
         <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sp_4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 617px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dbjs_4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 617px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sbdz_4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 617px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dqdz_4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 617px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_44_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 617px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_44_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 617px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_44_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 617px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_44_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 617px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_44_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 617px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_44_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 617px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
         <%--表2第五行--%>
         <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sp_5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 647px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dbjs_5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 647px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sbdz_5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 647px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dqdz_5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 647px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_45_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 647px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_45_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 647px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_45_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 647px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_45_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 647px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_45_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 647px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_45_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 647px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
         <%--表2第六行--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sp_6>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 676px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dbjs_6>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 676px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sbdz_6>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 676px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dqdz_6>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 676px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_46_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 676px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_46_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 676px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_46_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 676px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_46_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 676px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_46_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 676px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_46_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 676px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
         <%--表2第七行--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sp_7>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 706px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dbjs_7>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 706px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sbdz_7>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 706px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dqdz_7>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 706px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_47_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 706px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_47_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 706px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_47_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 706px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_47_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 706px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_47_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 706px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_47_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 706px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
         <%--表2第八行--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sp_8>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 736px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dbjs_8>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 736px; left: 349px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.sbdz_8>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 736px; left: 471px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_SL_5F3_5.dqdz_8>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 736px; left: 593px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_48_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 736px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_48_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 736px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_48_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 736px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_48_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 736px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_48_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 736px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_48_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 736px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 25px; right: 1213px;"></div>
     <%--表2第九行--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LDPLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 767px; left: 715px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LDCLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 767px; left: 837px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LMPLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 767px; left: 959px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LMCLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 767px; left: 1082px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LYPLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 767px; left: 1204px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs02_sbdz_4_LYCLJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:117px; display:block; top: 767px; left: 1325px; position:absolute;color:#4cff00;text-align:right; height: 26px; right: 1213px;"></div>


         <%--汉字隐藏--%>

        <%--棒图--%>
        </div>
        <div id="htmlContainer"></div>
</body>


</html>
