<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_klqc_klqf_clinker01_yaotoubilengji.aspx.cs" Inherits="Monitor_klqc.web.UI_Monitor.DCSMonitor.zc_nxjc_klqc_klqf.zc_nxjc_klqc_klqf_clinker01_yaotoubilengji" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>  
<script>
    publicData.organizationId = "zc_nxjc_klqc_klqf_clinker01";
    publicData.sceneName = "烧成窑头篦冷机";
</script>
</head>
<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="SubMonitorLayout" style="position: relative; background-image: url('/UI_Monitor/images/page/DCS/zc_nxjc_klqc_klqf/zc_nxjc_klqc_klqf_clinker01_yaotoubilengji.png'); width: 1481px; height: 722px; overflow: hidden;">
    
 <%--贴标签处--%>
        <%--马海峰--%>
        <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YTZ_T>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 149px; left: 133px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5701P01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 167px; left: 133px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_5702a11_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 251px; left: 31px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_5702a12_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 273px; left: 31px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_5702a13_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 293px; left: 31px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_5702a14_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 317px; left: 31px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_5702a15_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 335px; left: 31px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 280px; left: 187px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T02>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 280px; left: 251px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 280px; left: 310px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T04>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 317px; left: 187px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T05>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 317px; left: 253px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702T06>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 317px; left: 313px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702d13_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 307px; left: 393px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702d14_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 326px; left: 393px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702d15_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 343px; left: 393px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GPGD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 265px; left: 430px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702b11_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 373px; left: 441px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702b12_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 398px; left: 441px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702b13_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 420px; left: 441px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702d11_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 315px; left: 567px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702d12_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 341px; left: 567px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702d02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 315px; left: 636px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5702d03_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 339px; left: 636px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_LT_5702L01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 379px; left: 674px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_M5702dT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 241px; left: 373px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_4_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 18px; left: 333px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_4_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 39px; left: 333px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_4_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 63px; left: 333px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_5_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 20px; left: 427px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_5_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 42px; left: 427px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_5_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 64px; left: 427px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5706P01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 187px; left: 377px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702g1_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 114px; left: 529px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5702g2_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 114px; left: 635px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GSD_1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 242px; left: 555px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GSD_2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 260px; left: 555px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GSD_3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 276px; left: 555px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GSD_4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 294px; left: 555px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702T07>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 247px; left: 729px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5716Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 209px; left: 750px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_EDGD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 314px; left: 727px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SD_FK2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 340px; left: 727px; position: absolute; color:blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5719T03_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 46px; left: 852px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5717P01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 66px; left: 852px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5719P01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 53px; left: 1001px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5719T04_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 72px; left: 1001px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5718Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 110px; left: 978px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5719P01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 11px; left: 1114px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5721aZ01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 83px; left: 1228px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_AH5_57E_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 119px; left: 1233px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5721T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 141px; left: 1233px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5721MT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 161px; left: 1233px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5721MT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 181px; left: 1233px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5719T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 94px; left: 1058px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5719T02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 92px; left: 1165px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_XT_5722X01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 122px; left: 1331px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 143px; left: 1331px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 163px; left: 1331px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_R1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 183px; left: 1331px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VT_5721VT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 311px; left: 1289px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VT_5721VT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 333px; left: 1289px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YXWD_TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 541px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YB_P1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 560px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YB_P2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 576px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YB_P3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 594px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YB_P4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 611px; left: 897px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YWG_TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 578px; left: 1047px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M1_PP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 611px; left: 1047px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M2_PP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 628px; left: 1047px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M3_PP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 544px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M4_PP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 561px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YWG_TT2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 576px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M1_PP2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 609px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M2_PP2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 628px; left: 1200px; position: absolute; color: #4cff00; text-align: right; height: 12px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 477px; left: 137px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5708F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 498px; left: 137px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5708T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 516px; left: 137px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P02>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 479px; left: 224px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5709F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 497px; left: 224px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5709T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 514px; left: 224px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 480px; left: 308px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5710F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 499px; left: 308px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5710T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 516px; left: 308px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P04>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 477px; left: 393px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5711F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 498px; left: 392px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5711T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 516px; left: 392px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P05>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 478px; left: 474px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5712F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 496px; left: 474px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5712T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 515px; left: 475px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P061>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 477px; left: 553px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5713F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 499px; left: 553px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5713T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 515px; left: 553px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P07>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 476px; left: 640px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5714F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 498px; left: 640px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5714T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 517px; left: 640px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5702P08>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 478px; left: 722px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_FT_5715F01>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 499px; left: 722px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5715T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 516px; left: 722px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5708Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 613px; left: 102px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5709Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 612px; left: 191px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5710Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 615px; left: 276px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_11_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 601px; left: 390px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_11_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 622px; left: 390px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_11_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 641px; left: 391px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_12_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 601px; left: 476px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_12_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 620px; left: 476px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_12_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 639px; left: 476px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_13_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 603px; left: 559px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_13_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 620px; left: 559px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_13_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 639px; left: 559px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_14_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 604px; left: 643px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_14_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 620px; left: 643px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_14_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 640px; left: 643px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_15_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 602px; left: 725px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_15_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 621px; left: 725px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_15_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 640px; left: 725px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_08_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 654px; left: 142px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5709MT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 640px; left: 223px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5709MT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 663px; left: 223px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_AH3_57E_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 682px; left: 223px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5710MT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 640px; left: 305px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_5710MT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 660px; left: 305px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_AH4_57E_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 682px; left: 305px; position: absolute; color: #4cff00; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SD_FK>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 366px; left: 181px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YDGD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 345px; left: 181px; position: absolute; color: blue; text-align: right; height: 16px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_6600L01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 39px; display: block; top: 618px; left: 1352px; position: absolute; color: blue; text-align: right; height: 14px;"></div>
        <%--开关量--%>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_N55141AR_RD>BoolSignal" style="position: absolute; top: 231px; left: 275px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_N55113M_RD,dcs01_N55113M_RN,dcs01_N55113M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a1_1_RD>BoolSignal" style="position: absolute; top: 244px; left: 152px; height: 18px; width: 23px; bottom: 460px;" data-option="RelatedTags='dcs01_M57_2a1_1_RD,dcs01_M57_2a1_1_RN,dcs01_M57_2a1_1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a1_2_RD>BoolSignal" style="position: absolute; top: 268px; left: 152px; height: 18px; width: 23px;" data-option="RelatedTags='dcs01_M57_2a1_2_RD,dcs01_M57_2a1_2_RN,dcs01_M57_2a1_2_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a1_3_RD>BoolSignal" style="position: absolute; top: 291px; left: 152px; height: 18px; width: 23px;" data-option="RelatedTags='dcs01_M57_2a1_3_RD,dcs01_M57_2a1_3_RN,dcs01_M57_2a1_3_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a1_4_RD>BoolSignal" style="position: absolute; top: 315px; left: 152px; height: 18px; width: 23px; bottom: 389px;" data-option="RelatedTags='dcs01_M57_2a1_4_RD,dcs01_M57_2a1_4_RN,dcs01_M57_2a1_4_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a1_5_RD>BoolSignal" style="position: absolute; top: 337px; left: 152px; height: 18px; width: 23px;" data-option="RelatedTags='dcs01_M57_2a1_5_RD,dcs01_M57_2a1_5_RN,dcs01_M57_2a1_5_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_BLJ_RD>BoolSignal" style="position: absolute; top: 371px; left: 301px; height: 24px; width: 15px;" data-option="RelatedTags='dcs01_BLJ_RD,dcs01_BLJ_RN,dcs01_BLJ_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_57_26_RD>BoolSignal" style="position: absolute; top: 432px; left: 18px; height: 26px; width: 16px;" data-option="RelatedTags='dcs01_SCP_57_26_RD,dcs01_SCP_57_26_RN,dcs01_SCP_57_26_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_BLJ2_RD>BoolSignal" style="position: absolute; top: 316px; left: 826px; height: 27px; width: 16px;" data-option="RelatedTags='dcs01_BLJ2_RD,dcs01_BLJ2_RN,dcs01_BLJ2_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GPKZG_RD>BoolSignal" style="position: absolute; top: 270px; left: 513px; height: 29px; width: 19px;" data-option="RelatedTags='dcs01_GPKZG_RD,dcs01_GPKZG_RN,dcs01_GPKZG_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_02e_RD>BoolSignal" style="position: absolute; top: 399px; left: 790px; height: 29px; width: 19px;" data-option="RelatedTags='dcs01_M57_02e_RD,dcs01_M57_02e_RN',Display='00:yellowS,01:redSB,10:greenS,11:redSB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2b1_1_RD>BoolSignal" style="position: absolute; top: 377px; left: 559px; height: 15px; width: 23px;" data-option="RelatedTags='dcs01_M57_2b1_1_RD,dcs01_M57_2b1_1_RN,dcs01_M57_2b1_1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2b1_2_RD>BoolSignal" style="position: absolute; top: 399px; left: 559px; height: 15px; width: 23px;" data-option="RelatedTags='dcs01_M57_2b1_2_RD,dcs01_M57_2b1_2_RN,dcs01_M57_2b1_2_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2b1_3_RD>BoolSignal" style="position: absolute; top: 419px; left: 559px; height: 15px; width: 23px; right: 898px;" data-option="RelatedTags='dcs01_M57_2b1_3_RD,dcs01_M57_2b1_3_RN,dcs01_M57_2b1_3_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_57_02e_RD>BoolSignal" style="position: absolute; top: 231px; left: 275px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_SCP_57_02e_RD,dcs01_SCP_57_02e_RN,dcs01_SCP_57_02e_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2a2_RD>BoolSignal" style="position: absolute; top: 378px; left: 80px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2a2_RD,dcs01_M57_2a2_RN,dcs01_M57_2a2_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2d2_RD>BoolSignal" style="position: absolute; top: 350px; left: 335px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2d2_RD,dcs01_M57_2d2_RN,dcs01_M57_2d2_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2d1_4_RD>BoolSignal" style="position: absolute; top: 331px; left: 473px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2d1_4_RD,dcs01_M57_2d1_4_RN,dcs01_M57_2d1_4_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2d1_3_RD>BoolSignal" style="position: absolute; top: 330px; left: 502px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2d1_3_RD,dcs01_M57_2d1_3_RN,M57_2d1_3_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2d1_2_RD>BoolSignal" style="position: absolute; top: 330px; left: 529px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2d1_2_RD,dcs01_M57_2d1_2_RN,dcs01_M57_2d1_2_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2b2_RD>BoolSignal" style="position: absolute; top: 225px; left: 490px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2b2_RD,dcs01_M57_2b2_RN,dcs01_M57_2b2_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M714_V01_RD>BoolSignal" style="position: absolute; top: 188px; left: 490px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M714_V01_RD,dcs01_M714_V01_RN,dcs01_M714_V01_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_4_BP_RD>BoolSignal" style="position: absolute; top: 87px; left: 377px; height: 22px; width: 24px;" data-option="RelatedTags='M57_4_BP_RD,dcs01_M57_4_BP_RN,dcs01_M57_4_BP_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_5_BP_RD>BoolSignal" style="position: absolute; top: 87px; left: 440px; height: 22px; width: 24px; right: 1017px;" data-option="RelatedTags='dcs01_M57_5_BP_RD,dcs01_M57_5_BP_RN,dcs01_M57_5_BP_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2g1_RD>BoolSignal" style="position: absolute; top: 87px; left: 586px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2g1_RD,dcs01_M57_2g1_RN,dcs01_M57_2g1_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_2g2_RD>BoolSignal" style="position: absolute; top: 86px; left: 633px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_2g2_RD,dcs01_M57_2g2_RN,dcs01_M57_2g2_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_8_RD>BoolSignal" style="position: absolute; top: 572px; left: 182px; height: 22px; width: 24px; right: 1275px;" data-option="RelatedTags='dcs01_M57_8_RD,dcs01_M57_8_RN,dcs01_M57_8_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_09_RD>BoolSignal" style="position: absolute; top: 572px; height: 22px; width: 24px; right: 1190px;" data-option="RelatedTags='dcs01_M_57_09_RD,dcs01_M_57_09_HZ,dcs01_M_57_09_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_10_RD>BoolSignal" style="position: absolute; top: 572px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M_57_10_RD,dcs01_M_57_10_HZ,dcs01_M_57_10_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_11_BP_RD>BoolSignal" style="position: absolute; top: 572px; left: 429px; height: 22px; width: 24px; right: 1028px;" data-option="RelatedTags='dcs01_M57_11_BP_RD,dcs01_M57_11_BP_RN,dcs01_M57_11_BP_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_12_BP_RD>BoolSignal" style="position: absolute; top: 572px; left: 511px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_12_BP_RD,dcs01_M57_12_BP_RN,dcs01_M57_12_BP_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_13_BP_RD>BoolSignal" style="position: absolute; top: 572px; left: 596px; height: 22px; width: 24px; right: 861px;" data-option="RelatedTags='dcs01_M57_13_BP_RD,dcs01_M57_13_BP_RN,dcs01_M57_13_BP_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_14_BP_RD>BoolSignal" style="position: absolute; top: 572px; left: 679px; height: 22px; width: 24px; right: 778px;" data-option="RelatedTags='dcs01_M57_14_BP_RD,dcs01_M57_14_BP_RN,dcs01_M57_14_BP_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_15_BP_RD>BoolSignal" style="position: absolute; top: 572px; left: 761px; height: 22px; width: 24px;" data-option="RelatedTags='dcs01_M57_15_BP_RD,dcs01_M57_15_BP_RN,dcs01_M57_15_BP_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_SCP_77_7_RD>BoolSignal" style="position: absolute; top: 411px; left: 1369px; height: 17px; width: 18px;" data-option="RelatedTags='dcs01_SCP_77_7_RD,dcs01_SCP_77_7_RN,dcs01_SCP_77_7_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M77_8_RD>BoolSignal" style="position: absolute; top: 456px; left: 1406px; height: 13px; width: 14px;" data-option="RelatedTags='dcs01_M77_8_RD,dcs01_M77_8_RN,dcs01_M77_8_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M_57_21_RD>BoolSignal" style="position: absolute; top: 250px; left: 1360px; height: 31px; width: 32px;" data-option="RelatedTags='dcs01_M_57_21_RD,dcs01_M_57_21_HZ,dcs01_M_57_21_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_21f1_RD>BoolSignal" style="position: absolute; top: 289px; left: 1360px; height: 12px; width: 13px;" data-option="RelatedTags='dcs01_M57_21f1_RD,dcs01_M57_21f1_RN,dcs01_M57_21f1_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_21f2_RD>BoolSignal" style="position: absolute; top: 288px; left: 1380px; height: 13px; width: 14px;" data-option="RelatedTags='dcs01_M57_21f2_RD,dcs01_M57_21f2_RN,dcs01_M57_21f2_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_F_5719AR_RD>BoolSignal" style="position: absolute; top: 63px; left: 1150px; height: 18px; width: 17px;" data-option="RelatedTags='dcs01_F_5719AR_RD,dcs01_F_5719AR_RN,dcs01_F_5719AR_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_6_RD>BoolSignal" style="position: absolute; top: 128px; left: 378px; height: 53px; width: 16px;" data-option="RelatedTags='dcs01_M57_6_RD,dcs01_M57_6_RN,dcs01_M57_6_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_7_RD>BoolSignal" style="position: absolute; top: 130px; left: 440px; height: 51px; width: 16px;" data-option="RelatedTags='dcs01_M57_7_RD,dcs01_M57_7_RN,dcs01_M57_7_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M57_20_RD>BoolSignal" style="position: absolute; top: 388px; left: 1271px; height: 27px; width: 16px;" data-option="RelatedTags='dcs01_M57_20_RD,dcs01_M57_20_RN,dcs01_M57_20_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M65_1_RD>BoolSignal" style="position: absolute; top: 476px; left: 1341px; height: 13px; width: 23px;" data-option="RelatedTags='dcs01_M65_1_RD,dcs01_M65_1_RN,dcs01_M65_1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <%--汉字隐藏--%>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_8_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 561px; left: 125px; color: red; text-align: center; height: 14px; right: 1323px; bottom: 147px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_57_26_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 410px; left: 13px; color: red; text-align: center; height: 14px; right: 1435px; bottom: 298px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_57_26_YK>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 484px; left: 14px; color: red; text-align: center; height: 14px; right: 1414px; bottom: 224px;">远控手动</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_09_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 582px; left: 226px; color: red; text-align: center; height: 14px; right: 1222px; bottom: 126px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_M_57_10_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 585px; left: 306px; color: red; text-align: center; height: 14px; right: 1142px; bottom: 123px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_11_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 577px; left: 388px; color: red; text-align: center; height: 14px; right: 1060px; bottom: 131px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_12_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 574px; left: 471px; color: red; text-align: center; height: 14px; right: 977px; bottom: 134px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_13_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 575px; left: 555px; color: red; text-align: center; height: 14px; right: 893px; bottom: 133px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_14_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 577px; left: 639px; color: red; text-align: center; height: 14px; right: 816px; bottom: 131px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_15_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 574px; left: 722px; color: red; text-align: center; height: 14px; right: 726px; bottom: 134px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_09_ALM>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 559px; left: 225px; color: red; text-align: center; height: 14px; right: 1223px; bottom: 149px;">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_10_ALM>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 560px; left: 305px; color: red; text-align: center; height: 14px; right: 1143px; bottom: 148px;">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_BLJ_GZ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 416px; left: 293px; color: red; text-align: center; height: 14px; right: 1155px; bottom: 292px;">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_8_WB>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 577px; left: 116px; color: green; text-align: center; height: 14px; right: 1312px; bottom: 131px;">软起完毕</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_8_PL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 597px; left: 115px; color: green; text-align: center; height: 14px; bottom: 111px;">软起旁路</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5708Z01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 597px; left: 176px; color: green; text-align: center; height: 13px; right: 1276px; bottom: 112px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5709Z01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 598px; left: 261px; color: green; text-align: center; height: 13px; right: 1187px; bottom: 111px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5710Z01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 596px; left: 343px; color: green; text-align: center; height: 14px; right: 1107px; bottom: 112px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5708Z01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 642px; left: 186px; color: green; text-align: center; height: 14px; right: 1264px; bottom: 66px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5709Z01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 632px; left: 269px; color: green; text-align: center; height: 11px; right: 1178px; bottom: 79px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5710Z01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 627px; left: 352px; color: green; text-align: center; height: 14px; right: 1099px; bottom: 81px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_4_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 99px; left: 321px; color: red; text-align: center; height: 14px; right: 1127px; bottom: 609px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_5_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 99px; left: 483px; color: red; text-align: center; height: 14px; right: 965px; bottom: 609px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_57_02e_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 245px; left: 309px; color: red; text-align: center; height: 14px; right: 1139px; bottom: 463px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_02e_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 817px; color: red; text-align: center; height: 14px; right: 631px; bottom: 305px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_BLJ2_GZ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 358px; left: 814px; color: red; text-align: center; height: 14px; right: 634px; bottom: 350px;">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_6_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 132px; left: 323px; color: green; text-align: center; height: 14px; right: 1105px; bottom: 576px;">正限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_6_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 157px; left: 323px; color: green; text-align: center; height: 14px; right: 1105px; bottom: 551px;">反限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_7_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 133px; left: 461px; color: green; text-align: center; height: 14px; right: 967px; bottom: 575px;">正限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_7_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 158px; left: 461px; color: green; text-align: center; height: 14px; right: 967px; bottom: 550px;">反限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5716Z01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 190px; left: 811px; color: green; text-align: center; height: 14px; right: 634px; bottom: 518px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5716Z01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 241px; left: 809px; color: green; text-align: center; height: 14px; right: 634px; bottom: 467px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5718Z01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 129px; left: 972px; color: green; text-align: center; height: 14px; right: 473px; bottom: 579px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5718Z01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 129px; left: 1038px; color: green; text-align: center; height: 14px; right: 405px; bottom: 579px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5721aZ01_LIM1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 60px; left: 1217px; color: green; text-align: center; height: 14px; bottom: 648px;">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5721aZ01_LIM2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 58px; left: 1280px; color: green; text-align: center; height: 14px; right: 163px; bottom: 650px;">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M57_20_SD>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 385px; left: 1171px; color: green; text-align: center; height: 14px; right: 245px; bottom: 323px;">速度开关</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M65_1_SD>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 460px; left: 1239px; color: green; text-align: center; height: 18px; right: 167px; bottom: 244px;">速度信号</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_STB>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 231px; left: 1403px; color: green; text-align: center; height: 14px; right: 12px; bottom: 477px;">待机状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_GP>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; top: 251px; left: 1405px; color: green; text-align: center; height: 14px; right: 12px; bottom: 457px;">工频状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_BP>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1416px; color: green; text-align: center; height: 14px; right: 12px; bottom: 437px;">变频状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_5719AR_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1177px; color: red; text-align: center; height: 14px; right: 271px; bottom: 658px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_F_5719AR_GW>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1177px; color: red; text-align: center; height: 14px; right: 271px; bottom: 638px;">高温</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_QFT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1424px; color: red; text-align: center; height: 14px; right: 12px; bottom: 564px;">轻故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_ZFT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1417px; color: red; text-align: center; height: 14px; right: 12px; bottom: 542px;">重故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21HAV_BP_TC>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1401px; color: red; text-align: center; height: 14px; right: 12px; bottom: 504px;">变频器退出</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M65_1_LS>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 944px; color: red; text-align: center; height: 14px; right: 504px; bottom: 233px;">拉绳</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M65_1_PP1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1081px; color: red; text-align: center; height: 14px; right: 367px; bottom: 233px;">跑偏1</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M65_1_PP2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1146px; color: red; text-align: center; height: 14px; right: 302px; bottom: 233px;">跑偏2</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M_57_21_FT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1385px; color: red; text-align: center; height: 14px; right: 45px; bottom: 404px;">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M5721VT_ALMa1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1388px; color: red; text-align: center; height: 14px; right: 21px; bottom: 385px;">振动A报警1</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M5721VT_ALMa2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1388px; color: red; text-align: center; height: 14px; right: 21px; bottom: 366px;">振动A报警2</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M5721VT_ALMb1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1388px; color: red; text-align: center; height: 14px; right: 21px; bottom: 348px;">振动B报警1</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M5721VT_ALMb2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 13px; left: 1388px; color: red; text-align: center; height: 14px; right: 21px; bottom: 325px;">振动B报警2</div>
    
    </div>
</body>
</html>
