<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_klqc_klqf_clinker01_yuanliaomojimeiqichuli.aspx.cs" Inherits="Monitor_klqc.web.UI_Monitor.DCSMonitor.zc_nxjc_klqc_klqf.zc_nxjc_klqc_klqf_clinker01_yuanliaomojimeiqichuli" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
      <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>  
<script>
    publicData.organizationId = "zc_nxjc_klqc_klqf_clinker01";
    publicData.sceneName = "原料粉磨及废气处理";

</script>
</head>
<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="SubMonitorLayout" style="position: relative; background-image: url('/UI_Monitor/images/page/DCS/zc_nxjc_klqc_klqf/zc_nxjc_klqc_klqf_clinker01_yuanliaomojimeiqichuli.png'); width: 1492px; height: 781px; overflow: hidden;">
    
    <%--贴标签处--%>
     <%--贴标签处--%>
    
        <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZXJC_SO2_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 27px; left: 100px; position:absolute;color:#4cff00;text-align:right;font-size:12px;bottom: 736px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZXJC_NO_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 54px; left: 100px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 709px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZXJC_KL_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 78px; left: 100px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 685px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YW_ATY_F_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 103px; left: 100px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 660px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZXJC_O2_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 127px; left: 100px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 636px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZXJC_T_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 30px; left: 216px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 733px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZXJC_LS_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 54px; left: 216px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 709px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZXJC_P_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 79px; left: 216px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 684px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TX_HZ_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 104px; left: 216px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 659px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TX_HZ1_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 128px; left: 216px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 635px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_54_09PTO1_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 18px; left: 329px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 745px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_54_09MTO1_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 38px; left: 329px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 725px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_54_09MTO2_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 59px; left: 330px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 704px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VT_5409V01a_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 82px; left: 330px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 681px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VT_5409V01b_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 106px; left: 331px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 657px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5409aZ01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 47px; left: 463px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 716px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_JDZ_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 85px; left: 519px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 678px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP2_54_4_T2_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 103px; left: 520px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 660px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_54_9_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 140px; left: 494px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 623px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_54_9_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 163px; left: 494px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 600px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_54_9_SP_R1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 185px; left: 494px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 578px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_YWBDCY_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 36px; left: 592px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 727px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_54_04PO1_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 88px; left: 684px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 675px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP2_54_4_T1_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 106px; left: 683px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 657px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5415Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 65px; left: 787px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 698px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5414Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 137px; left: 778px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 626px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5413P01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 136px; left: 850px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 627px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5413Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 138px; left: 918px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 625px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5411Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 89px; left: 1042px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 674px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5410Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 45px; left: 1126px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 718px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_5401P01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 176px; left: 1070px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 587px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_T_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 53px; left: 1211px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 710px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_F_R>DCS'" style="width:47px; display:block; top: 75px; left: 1213px; position:absolute;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_F_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 97px; left: 1211px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 666px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_YTP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 121px; left: 1212px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 642px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_QTP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 143px; left: 1211px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 620px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZST_L_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 52px; left: 1323px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 711px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_51_08_VFD1_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 74px; left: 1322px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 689px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_51_08_VFD2_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 97px; left: 1323px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 666px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_SDT_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 120px; left: 1321px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 643px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_CKT_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 144px; left: 1322px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_54_1_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 195px; left: 1212px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 568px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_54_1_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 218px; left: 1211px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 545px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1d_T1_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 243px; left: 1211px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 520px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1d_T2_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 267px; left: 1211px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 496px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3518_AR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 168px; left: 40px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 597px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_41_5_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 208px; left: 88px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 557px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_41_5_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 224px; left: 87px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 541px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_41_5_SP_R1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 241px; left: 88px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 524px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_WT_4105aW01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 283px; left: 183px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 482px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_WT_4105aW01_TPR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 300px; left: 182px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 465px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_09_1_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 374px; left: 76px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 391px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_09_2_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 393px; left: 75px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 372px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_14_1_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 340px; left: 254px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 425px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_14_2_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 358px; left: 253px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 407px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD676R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:36px; display:block; top: 426px; left: 143px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 341px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_4113Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:37px; display:block; top: 442px; left: 141px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 325px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD680R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:34px; display:block; top: 423px; left: 206px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 343px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_4113Z02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:38px; display:block; top: 440px; left: 203px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 327px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_41_08PO2_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 355px; left: 412px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 410px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_41_08PO1_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 449px; left: 334px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 316px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_5412Z01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 505px; left: 364px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 260px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_4116P01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 457px; left: 490px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 308px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_4116T01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 476px; left: 490px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 289px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_15_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 267px; left: 548px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 498px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_15_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 286px; left: 548px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 479px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_15_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 305px; left: 547px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 460px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_41_15TO1_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 323px; left: 548px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 442px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_TT_4116T02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 361px; left: 577px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 404px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PT_4116P02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 382px; left: 584px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 383px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ZT_4117aZ01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:42px; display:block; top: 368px; left: 681px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 397px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_41_17TO1_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 283px; left: 857px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 480px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_41_17MT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 304px; left: 856px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 459px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_41_17MT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 326px; left: 856px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 437px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VT_4117V01a_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 348px; left: 857px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 415px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VT_4117V01b_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 369px; left: 856px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 394px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 406px; left: 769px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 357px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_SP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 428px; left: 770px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 335px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_SP_R1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 451px; left: 771px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 312px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3512_PB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 639px; left: 149px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 126px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3515_PB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 639px; left: 208px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 126px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3514_PB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 639px; left: 265px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 126px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3513_PB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 638px; left: 324px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 127px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_17_4_PB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 639px; left: 383px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 126px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3512_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 675px; left: 149px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 90px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3515_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 677px; left: 208px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 88px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3514_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 677px; left: 267px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 88px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3513_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 676px; left: 325px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 89px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_17_4_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 676px; left: 384px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 89px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3512_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 694px; left: 148px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 71px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3515_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 695px; left: 208px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 70px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3514_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 693px; left: 267px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 72px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3513_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 694px; left: 325px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 71px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_17_4_FB_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 693px; left: 383px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 72px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3512_LJR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 712px; left: 151px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 53px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3515_LJR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 713px; left: 210px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 52px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3514_LJR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 713px; left: 268px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 52px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3513_LJR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 716px; left: 327px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 49px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_17_4_LJR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 716px; left: 384px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 49px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GYJGFC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 660px; left: 530px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 108px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD604R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 677px; left: 529px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 86px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD656R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 693px; left: 529px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 70px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD664R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 709px; left: 528px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 54px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD632R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 727px; left: 529px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 36px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD640R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 744px; left: 529px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 19px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD644R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 660px; left: 680px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 103px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD608R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 678px; left: 679px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 85px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD612R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 694px; left: 680px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 69px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD616R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 710px; left: 679px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 53px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD672R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 729px; left: 679px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 34px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GYJYLC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 746px; left: 678px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 17px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD600R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 675px; left: 857px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 88px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD660R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 691px; left: 856px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 72px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD668R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 709px; left: 856px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 54px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD636R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 725px; left: 855px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 38px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD652R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 743px; left: 855px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 20px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD648R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 674px; left: 1000px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 89px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD620R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 690px; left: 1000px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 73px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD624R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 706px; left: 1001px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 57px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD628R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 724px; left: 1000px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 39px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_4113P01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 740px; left: 1000px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 23px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SUMT_SET_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 584px; left: 257px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 179px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SUMT_PV_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:41px; display:block; top: 583px; left: 394px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 180px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_LT_4208L01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:50px; display:block; top: 646px; left: 1325px; position:absolute;color:blue;text-align:right;font-size:12px; bottom: 115px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M42_01_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 514px; left: 1276px; position:absolute;color:#4cff00;text-align:right;font-size:12px; bottom: 248px;"></div>
        .


        <%--汉字隐藏--%>
        <div id="zc_nxjc_klqc_klqf>dcs01_M35_18_SD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 154px; left: 41px; color:#4cff00;text-align:center">速度信号</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_01_RN>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 190px; left: 63px; color:#4cff00;text-align:center">运行</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_PQD800_2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 183px; left: 183px; color:#4cff00;text-align:center">动辊减速机油泵运行</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_PQD800_6>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 198px; left: 183px; color:#4cff00;text-align:center">定辊减速机油泵运行</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_PQD802_5>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 211px; left: 183px; color:#4cff00;text-align:center">动辊主电机运行</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_PQD803_0>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 224px; left: 183px; color:#4cff00;text-align:center">定辊主电机运行</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_PQD808_6>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 237px; left: 183px; color:#4cff00;text-align:center">活动辊减速机油站正常</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_PQD808_7DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 250px; left: 183px; color:#4cff00;text-align:center">固定辊减速机油站正常</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_PQD809_0>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 263px; left: 183px; color:#4cff00;text-align:center">液压油站正常</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_14_1_1_SD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 263px; left: 290px; color:#4cff00;text-align:center">速度信号</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_9_ST>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 166px; left: 332px; color:#4cff00;text-align:center">变频待机</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_9_BP>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 181px; left: 332px; color:#4cff00;text-align:center">变频状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_9_GP>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 194px; left: 332px; color:#4cff00;text-align:center">工频状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_9_QFT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 134px; left: 333px; color:red;text-align:center">轻故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_9_ZFT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 149px; left: 333px; color:red;text-align:center">重故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M54_9_ALM>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 131px; left: 382px; color:red;text-align:center">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M54_9_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 147px; left: 383px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VT_5409V01ab_ALM>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 59px; left: 413px; color:red;text-align:center">测振仪报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VT_5409V01ab_AL2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 72px; left: 414px; color:red;text-align:center">测振仪报警2</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT5409aZ01_LIM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 69px; left: 473px; color:#4cff00;text-align:center">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT5409aZ01_LIM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 69px; left: 505px; color:#4cff00;text-align:center">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5415Z01_LIM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 45px; left: 756px; color:#4cff00;text-align:center">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5415Z01_LIM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 44px; left: 805px; color:#4cff00;text-align:center">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5414Z01_LIM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 111px; left: 786px; color:#4cff00;text-align:center">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5414Z01_LIM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 110px; left: 834px; color:#4cff00;text-align:center">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5413Z01_LIM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 113px; left: 907px; color:#4cff00;text-align:center">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5413Z01_LIM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 114px; left: 954px; color:#4cff00;text-align:center">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5411Z01_LIM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 66px; left: 1044px; color:#4cff00;text-align:center">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5411Z01_LIM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 65px; left: 1086px; color:#4cff00;text-align:center">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5410Z01_LIM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 32px; left: 1115px; color:#4cff00;text-align:center">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5410Z01_LIM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 62px; left: 1114px; color:#4cff00;text-align:center">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP2_54_4_THH>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 90px; left: 652px; color:red;text-align:center">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP2_54_4_TH>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 104px; left: 651px; color:red;text-align:center">高温报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_15_EST>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 271px; left: 496px; color:red;text-align:center">急停</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_15_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 285px; left: 497px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_BP_TC>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 276px; left: 754px; color:red;text-align:center">变频退出</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_QFT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 290px; left: 755px; color:red;text-align:center">轻故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_ZFT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 303px; left: 754px; color:red;text-align:center">重故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_ST>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 315px; left: 753px; color:#4cff00;text-align:center">变频待机</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_BP>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 328px; left: 753px; color:#4cff00;text-align:center">变频状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_GP>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 340px; left: 750px; color:#4cff00;text-align:center">工频状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT4117aZ01_LIM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 344px; left: 686px; color:#4cff00;text-align:center">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT4117aZ01_LIM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 345px; left: 726px; color:#4cff00;text-align:center">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_17_ALM>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 340px; left: 827px; color:red;text-align:center">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_17_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 354px; left: 827px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VT_4117V01ab_FB2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 398px; left: 853px; color:red;text-align:center">测振仪报警2</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VT_4117V01ab_FB>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 413px; left: 854px; color:red;text-align:center">测振仪报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M4122_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 408px; left: 964px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1d_MZRN>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 203px; left: 1053px; color:#4cff00;text-align:center">检测柜慢转运行</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1d_YX>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 218px; left: 1053px; color:#4cff00;text-align:center">检测柜允许风机启动</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1d_LOCK>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 233px; left: 1051px; color:red;text-align:center">检测柜主机跳闸联锁</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1d_CW1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 246px; left: 1024px; color:red;text-align:center; bottom: 525px;">检测柜电机轴承测温超限</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1d_CW2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 261px; left: 999px; color:red;text-align:center">检测柜点击定子绕组测温超限</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1d_CW3>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 275px; left: 1017px; color:red;text-align:center">检测柜风机轴承温度超限</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1d_CZ>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 288px; left: 1018px; color:red;text-align:center">检测柜风机轴承振动超限</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1d_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 302px; left: 1019px; color:red;text-align:center">检测柜综合故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_1_BP_TC>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 315px; left: 1032px; color:red;text-align:center">变频退出</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_1_QFT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 327px; left: 1037px; color:red;text-align:center">轻故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_1_ZFT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 340px; left: 1037px; color:red;text-align:center">重故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_1_GP>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 353px; left: 1031px; color:#4cff00;text-align:center">工频状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1b_YALM>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 366px; left: 1030px; color:red;text-align:center">系统预报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1b_YX>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 356px; left: 1095px; color:#4cff00;text-align:center">允许主机工作</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_1_STDCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 340px; left: 1077px; color:#4cff00;text-align:center">变频待机</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_54_1_BP>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 339px; left: 1130px; color:#4cff00;text-align:center">变频状态</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1b_JRQ_RN>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 371px; left: 1100px; color:#4cff00;text-align:center">加热器运行</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M54_03_SD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 415px; left: 1094px; color:#4cff00;text-align:center">速度信号</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M54_2b_SD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 349px; left: 1264px; color:#4cff00;text-align:center">速度信号</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M54_2a_SD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 337px; left: 1325px; color:#4cff00;text-align:center">速度信号</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M54_2c_SD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 355px; left: 1363px; color:#4cff00;text-align:center">速度信号</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_ALM>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 283px; left: 1377px; color:red;text-align:center">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_AQMS>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 41px; left: 1416px; color:#4cff00;text-align:center">安全模式</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP25108_VFD1_RN>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 56px; left: 1415px; color:#4cff00;text-align:center">VFD1运行</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP25108_VFD2_RN>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 71px; left: 1416px; color:#4cff00;text-align:center">VFD2运行</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_YCMS>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 84px; left: 1416px; color:#4cff00;text-align:center">远程模式</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_G2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 97px; left: 1430px; color:#4cff00;text-align:center">分组2</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_G3>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 109px; left: 1430px; color:#4cff00;text-align:center">分组3</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_G4>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 123px; left: 1430px; color:#4cff00;text-align:center">分组4</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_CKPKG>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 138px; left: 1397px; color:#4cff00;text-align:center">出口液体压力开关</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_RKPKG>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 151px; left: 1397px; color:#4cff00;text-align:center">入口气体压力开关</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M42_1_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 549px; left: 1251px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M42_1_EST>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 562px; left: 1251px; color:red;text-align:center">急停</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M42_1_LW>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 576px; left: 1253px; color:red;text-align:center">高料位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M42_1_WD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 589px; left: 1253px; color:red;text-align:center">温度开关</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M42_1_PPD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 604px; left: 1252px; color:red;text-align:center">下部跑偏</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M42_1_PPU>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 617px; left: 1252px; color:red;text-align:center">上部跑偏</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M42_1_WB>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 562px; left: 1195px; color:#4cff00;text-align:center">启动完毕</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M42_1_SD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 575px; left: 1195px; color:#4cff00;text-align:center">速度开关</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M42_1_PL>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 587px; left: 1195px; color:#4cff00;text-align:center">旁路</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M42_01_2_LHQ>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 674px; left: 1202px; color:#4cff00;text-align:center">离合器位置</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_9_1_1_SD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 311px; left: 71px; color:#4cff00;text-align:center">速度信号</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_41_5_EST>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 273px; left: 24px; color:red;text-align:center">急停</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_41_3_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 277px; left: 60px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_VFD_41_5_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 296px; left: 13px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_41_4b_FX>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 262px; left: 122px; color:red;text-align:center">发现金属</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_41_4b_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 274px; left: 137px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_WT_4105aW01_ALM>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 316px; left: 124px; color:red;text-align:center">皮带秤报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_WT_4110aW01_ALM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 379px; left: 165px; color:red;text-align:center">上限报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_WT_4110aW01_ALM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 394px; left: 167px; color:red;text-align:center">下限报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_06_LIM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 348px; left: 3px; color:#4cff00;text-align:center">反限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_06_LIM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 348px; left: 54px; color:#4cff00;text-align:center">正限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_09_2_LHQ>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 422px; left: 78px; color:#4cff00;text-align:center">离合器位置</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_PQD802_2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 409px; left: 157px; color:#4cff00;text-align:center">启动阀开</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_PQD802_3>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 407px; left: 217px; color:#4cff00;text-align:center">启动阀关</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_9_1_1_LW>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 456px; left: 73px; color:red;text-align:center">高料位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_9_1_1_FT1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 468px; left: 72px; color:red;text-align:center">1#故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_9_1_1_EST>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 480px; left: 73px; color:red;text-align:center">1#急停</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_9_1_2_FT1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 492px; left: 72px; color:red;text-align:center">2#故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_9_1_2_EST>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 505px; left: 74px; color:red;text-align:center">2#急停</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_14_1_1_LW>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 428px; left: 285px; color:red;text-align:center">高料位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_14_1_1_FT1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 441px; left: 284px; color:red;text-align:center">1#故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_14_1_1_EST>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 453px; left: 283px; color:red;text-align:center">1#急停</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_14_1_2_FT2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 469px; left: 284px; color:red;text-align:center">2#故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_14_1_2_EST>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 482px; left: 283px; color:red;text-align:center">2#急停</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ACC_41_13_1_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 460px; left: 164px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ACC_41_13_2_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 460px; left: 232px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_13_3_LHQ>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 535px; left: 67px; color:#4cff00;text-align:center">离合器位置</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_14_2_LHQ>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 536px; left: 286px; color:#4cff00;text-align:center">离合器位置</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_41_13_1_RD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 526px; left: 142px; color:yellow;text-align:center">水阻备妥</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_41_13_1_RN>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 541px; left: 141px; color:#4cff00;text-align:center">水阻应答</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_41_13_1_ALM>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 556px; left: 142px; color:red;text-align:center">水阻报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_41_13_2_RD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 527px; left: 210px; color:yellow;text-align:center">水阻备妥</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_41_13_2_RN>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 543px; left: 210px; color:#4cff00;text-align:center">水阻应答</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_41_13_2_ALM>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 556px; left: 210px; color:red;text-align:center">水阻报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5412Z01_LIM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 491px; left: 328px; color:#4cff00;text-align:center">开位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_ZT_5412Z01_LIM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 523px; left: 329px; color:#4cff00;text-align:center">关位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_SCP_42_6_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 514px; left: 1400px; color:red;text-align:center">故障</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M54_8_SD>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 487px; left: 1034px; color:#4cff00;text-align:center">速度信号</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_24_LIM1>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 524px; left: 1157px; color:#4cff00;text-align:center">正限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M41_24_LIM2>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 561px; left: 1158px; color:#4cff00;text-align:center">反限位</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M54_1_ALM>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 235px; left: 1173px; color:red;text-align:center">报警</div>
        <div id="zc_nxjc_klqc_klqf>dcs01_M54_1_FT>DCS" class="TextDisplay" style="position:absolute;font-size:10px; top: 249px; left: 1173px; color:red;text-align:center">故障</div>


   <%--开关量--%>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M35_18_RD>BoolSignal" style="position: absolute; top:157px; left: 97px; height: 17px; width: 17px;"data-option="RelatedTags='dcs01_M35_18_RD,dcs01_M35_18_RN,dcs01_M35_18_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_41_5_BP_RD>BoolSignal" style="position: absolute; top:290px; left: 36px; height: 17px; width: 17px;"data-option="RelatedTags='dcs01_VFD_41_5_BP_RD,dcs01_VFD_41_5_BP_RN,dcs01_VFD_41_5_BP_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_WT_4105aW01_RD>BoolSignal" style="position: absolute; top:290px; left: 161px; height: 17px; width: 17px;"data-option="RelatedTags='dcs01_WT_4105aW01_RD,dcs01_WT_4105aW01_RN,dcs01_WT_4105aW01_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP2_54_4_RD>BoolSignal" style="position: absolute; top:68px; left: 642px; height: 17px; width: 17px;"data-option="RelatedTags='dcs01_SCP2_54_4_RD,dcs01_SCP2_54_4_YX,dcs01_SCP2_54_4_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_9_RD>BoolSignal" style="position: absolute; top:122px; left: 449px; height: 22px; width: 22px;"data-option="RelatedTags='dcs01_M54_9_RD,dcs01_M54_9_HZ,dcs01_M54_9_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_15_BP_RD>BoolSignal" style="position: absolute; top:244px; left: 453px; height: 22px; width: 22px;"data-option="RelatedTags='dcs01_M41_15_BP_RD,dcs01_M41_15_BP_RN,dcs01_M41_15_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_09Mf1_RD>BoolSignal" style="position: absolute; top:146px; left: 442px; height: 12px; width: 12px;"data-option="RelatedTags='dcs01_M54_09Mf1_RD,dcs01_M54_09Mf1_RN,dcs01_M54_09Mf1_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_09Mf2_RD>BoolSignal" style="position: absolute; top:145px; left: 466px; height: 12px; width: 12px;"data-option="RelatedTags='dcs01_M54_09Mf2_RD,dcs01_M54_09Mf2_RN,dcs01_M54_09Mf2_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_PQD803_0>BoolSignal" style="position: absolute; top:486px; left: 180px; height: 22px; width: 22px;"data-option="RelatedTags='dcs01_GYJ_ZDJDR_RD,dcs01_PQD803_0,dcs01_GYJ_ZDJDR_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GYJ_ZDJDR_RD>BoolSignal" style="position: absolute; top:487px; left: 223px; height: 22px; width: 22px;"data-option="RelatedTags='dcs01_GYJ_ZDJDR_RD,dcs01_PQD802_5,dcs01_GYJ_ZDJDR_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3512_RD>BoolSignal" style="position: absolute; top:621px; left: 180px; height: 17px; width: 17px;"data-option="RelatedTags='dcs01_3512_RD,dcs01_3512_RN,dcs01_3512_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3515_RD>BoolSignal" style="position: absolute; top:621px; left: 238px; height: 17px; width: 17px;"data-option="RelatedTags='dcs01_3515_RD,dcs01_3515_RN,dcs01_3515_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3514_RD>BoolSignal" style="position: absolute; top:620px; left: 295px; height: 17px; width: 17px;"data-option="RelatedTags='dcs01_3514_RD,dcs01_3514_RN,dcs01_3514_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_3513_RD>BoolSignal" style="position: absolute; top:620px; left: 354px; height: 17px; width: 17px;"data-option="RelatedTags='dcs01_3513_RD,dcs01_3513_RN,dcs01_3513_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_19_RD>BoolSignal" style="position: absolute; top:618px; left: 690px; height: 20px; width: 20px;"data-option="RelatedTags='dcs01_M41_19_RD,dcs01_M41_19_RN,dcs01_M41_19_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_20_RD>BoolSignal" style="position: absolute; top:628px; left: 893px; height: 20px; width: 20px;"data-option="RelatedTags='dcs01_M41_20_RD,dcs01_M41_20_RN,dcs01_M41_20_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_21_RD>BoolSignal" style="position: absolute; top:639px; left: 1082px; height: 20px; width: 20px;"data-option="RelatedTags='dcs01_M41_21_RD,dcs01_M41_21_RN,dcs01_M41_21_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M42_3_RD>BoolSignal" style="position: absolute; top:557px; left: 1280px; height: 14px; width: 14px;"data-option="RelatedTags='dcs01_M42_3_RD,dcs01_M42_3_RN,dcs01_M42_3_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M42_5_RD>BoolSignal" style="position: absolute; top:604px; left: 1323px; height: 14px; width: 14px;"data-option="RelatedTags='dcs01_M42_5_RD,dcs01_M42_5_RN,dcs01_M42_5_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_42_6_RD>BoolSignal" style="position: absolute; top:534px; left: 1438px; height: 14px; width: 14px;"data-option="RelatedTags='dcs01_SCP_42_6_RD,dcs01_SCP_42_6_RN,dcs01_SCP_42_6_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M42_7_RD>BoolSignal" style="position: absolute; top:489px; left: 1405px; height: 13px; width: 13px;"data-option="RelatedTags='dcs01_M42_7_RD,dcs01_M42_7_RN,dcs01_M42_7_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_2b_RD>BoolSignal" style="position: absolute; top:373px; left: 1383px; height: 16px; width: 16px;"data-option="RelatedTags='dcs01_M54_2b_RD,dcs01_M54_2b_RN,dcs01_M54_2b_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_2c_RD>BoolSignal" style="position: absolute; top:368px; left: 1287px; height: 16px; width: 16px;"data-option="RelatedTags='dcs01_M54_2c_RD,dcs01_M54_2c_RN,dcs01_M54_2c_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M4122_RD>BoolSignal" style="position: absolute; top:387px; left: 966px; height: 13px; width: 13px;"data-option="RelatedTags='dcs01_M4122_RD,dcs01_M4122_RN,dcs01_M4122_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_01Mf1_RD>BoolSignal" style="position: absolute; top:322px; left: 1136px; height: 13px; width: 13px;"data-option="RelatedTags='dcs01_M54_01Mf1_RD,dcs01_M54_01Mf1_RN,dcs01_M54_01Mf1_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_01Mf2_RD>BoolSignal" style="position: absolute; top:323px; left: 1167px; height: 13px; width: 13px;"data-option="RelatedTags='dcs01_M54_01Mf2_RD,dcs01_M54_01Mf2_RN,dcs01_M54_01Mf2_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_1_RD>BoolSignal" style="position: absolute; top:288px; left: 1141px; height: 31px; width: 31px;"data-option="RelatedTags='dcs01_M54_1_RD,dcs01_M54_1_HZ,dcs01_M54_1_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_RD>BoolSignal" style="position: absolute; top:129px; left: 414px; height: 26px; width: 16px;"data-option="RelatedTags='dcs01_VFD_41_17_RD,dcs01_VFD_41_17_RN,dcs01_VFD_41_17_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_14_1_1_RD>BoolSignal" style="position: absolute; top:282px; left: 279px; height: 14px; width: 15px;"data-option="RelatedTags='dcs01_M41_14_1_1_RD,dcs01_M41_14_1_1_RN1,dcs01_M41_14_1_1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_9_1_1_RD>BoolSignal" style="position: absolute; top:337px; left: 99px; height: 15px; width: 16px;"data-option="RelatedTags='dcs01_M41_9_1_1_RD,dcs01_M41_9_1_1_WB1,dcs01_M41_9_1_1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_41_3_RD>BoolSignal" style="position: absolute; top:283px; left: 85px; height: 9px; width: 27px; right: 1380px;"data-option="RelatedTags='dcs01_SCP_41_3_RD,dcs01_SCP_41_3_RN,dcs01_SCP_41_3_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_14_1_2_RD>BoolSignal" style="position: absolute; top:298px; left: 280px; height: 15px; width: 15px;"data-option="RelatedTags='dcs01_M41_14_1_2_RD,dcs01_M41_14_1_2_RN,dcs01_M41_14_1_1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_9_1_2_RD>BoolSignal" style="position: absolute; top:352px; left: 99px; height: 15px; width: 15px;"data-option="RelatedTags='dcs01_M41_9_1_2_RD,dcs01_M41_9_1_2_RN2,dcs01_M41_9_1_1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_09_2_RD>BoolSignal" style="position: absolute; top:437px; left: 102px; height: 15px; width: 13px;"data-option="RelatedTags='dcs01_M41_09_2_RD,dcs01_M41_09_2_RN,dcs01_M41_09_2_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ACC_41_13_1_RD>BoolSignal" style="position: absolute; top:457px; left: 141px; height: 15px; width: 13px;"data-option="RelatedTags='dcs01_ACC_41_13_1_RD,dcs01_ACC_41_13_1_RN,dcs01_ACC_41_13_1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_ACC_41_13_2_RD>BoolSignal" style="position: absolute; top:454px; left: 257px; height: 18px; width: 15px;"data-option="RelatedTags='dcs01_ACC_41_13_2_RD,dcs01_ACC_41_13_2_RN,dcs01_ACC_41_13_2_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_13_3_RD>BoolSignal" style="position: absolute; top:509px; left: 112px; height: 15px; width: 15px;"data-option="RelatedTags='dcs01_M41_13_3_RD,dcs01_M41_13_3_RN,dcs01_M41_13_3_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_GYJ_YZDR_RD>BoolSignal" style="position: absolute; top:498px; left: 260px; height: 23px; width: 15px;"data-option="RelatedTags='dcs01_GYJ_YZDR_RD,dcs01_GYJ_YZDR_RN,dcs01_GYJ_YZDR_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_14_2_RD>BoolSignal" style="position: absolute; top:553px; left: 319px; height: 15px; width: 15px;"data-option="RelatedTags='dcs01_M41_14_2_RD,dcs01_M41_14_2_RN,dcs01_M41_14_2_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_17_4_1_RD>BoolSignal" style="position: absolute; top:621px; left: 382px; height: 15px; width: 11px;"data-option="RelatedTags='dcs01_SCP_17_4_1_RD,dcs01_SCP_17_4_1_RN,dcs01_SCP_17_4_1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_17_4_2_RD>BoolSignal" style="position: absolute; top:621px; left: 418px; height: 15px; width: 11px;"data-option="RelatedTags='dcs01_SCP_17_4_2_RD,dcs01_SCP_17_4_2_RN,dcs01_SCP_17_4_2_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M42_01_2_RD>BoolSignal" style="position: absolute; top:662px; left: 1260px; height: 15px; width: 15px;"data-option="RelatedTags='dcs01_M42_01_2_RD,dcs01_M42_01_2_RN,dcs01_M42_01_2_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_8_RD>BoolSignal" style="position: absolute; top:495px; left: 903px; height: 21px; width: 22px;"data-option="RelatedTags='dcs01_M54_8_RD,dcs01_M54_8_RN,dcs01_M54_8_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_03_RD>BoolSignal" style="position: absolute; top:427px; left: 1038px; height: 22px; width: 22px;"data-option="RelatedTags='dcs01_M54_03_RD,dcs01_M54_03_RN,dcs01_M54_03_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_7_RD>BoolSignal" style="position: absolute; top:254px; left: 681px; height: 22px; width: 22px;"data-option="RelatedTags='dcs01_M54_7_RD,dcs01_M54_7_RN,dcs01_M54_7_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_41_17_RN>BoolSignal" style="position: absolute; top:386px; left: 734px; height: 26px; width: 17px;"data-option="RelatedTags='dcs01_VFD_41_17_RD,dcs01_VFD_41_17_RN,dcs01_VFD_41_17_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_17EE_RD>BoolSignal" style="position: absolute; top:374px; left: 756px; height: 18px; width: 17px;"data-option="RelatedTags='dcs01_M41_17EE_RD,dcs01_M41_17EE_RN,dcs01_M41_17EE_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP_54_1b_RD>BoolSignal" style="position: absolute; top:307px; left: 1114px; height: 22px; width: 12px; right: 366px;"data-option="RelatedTags='dcs01_SCP_54_1b_RD,dcs01_SCP_54_1b_1_RN,dcs01_SCP_54_1b_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_VFD_54_1_RD>BoolSignal" style="position: absolute; top:310px; left: 1192px; height: 26px; width: 17px;"data-option="RelatedTags='dcs01_VFD_54_1_RD,dcs01_VFD_54_1_RN,dcs01_VFD_54_1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_2a_RN2>BoolSignal" style="position: absolute; top:323px; left: 1267px; height: 18px; width: 17px;"data-option="RelatedTags='dcs01_M54_2a_RD,dcs01_M54_2a_RN2,dcs01_M54_2a_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M54_2a_RD>BoolSignal" style="position: absolute; top:325px; left: 1383px; height: 15px; width: 17px;"data-option="RelatedTags='dcs01_M54_2a_RD,dcs01_M54_2a_RN1,dcs01_M54_2a_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_SCP2_51_08_RD>BoolSignal" style="position: absolute; top:274px; left: 1411px; height: 19px; width: 10px;"data-option="RelatedTags='dcs01_SCP2_51_08_RD,dcs01_SCP2_51_08_RN,dcs01_SCP2_51_08_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_17Mf1_RD>BoolSignal" style="position: absolute; top:384px; left: 777px; height: 13px; width: 13px;"data-option="RelatedTags='dcs01_M41_17Mf1_RD,dcs01_M41_17Mf1_RN,dcs01_M41_17Mf1_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_17Mf2_RD>BoolSignal" style="position: absolute; top:385px; left: 809px; height: 13px; width: 13px;"data-option="RelatedTags='dcs01_M41_17Mf2_RD,dcs01_M41_17Mf2_RN,dcs01_M41_17Mf2_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_klqc_klqf>dcs01_M41_17_RD>BoolSignal" style="position: absolute; top:352px; left: 783px; height: 31px; width: 31px;"data-option="RelatedTags='dcs01_M41_17_RD,dcs01_M41_17_HZ,dcs01_M41_17_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>

    </div>
</body>
   
</html>
