<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_znc_znf_clinker01_mxt.aspx.cs" Inherits="Monitor_znc.Web.UI_Monitor.DCSMonitor.zc_nxjc_znc_znf.zc_nxjc_znc_znf_clinker01_mxt" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>

    <script>
        publicData.organizationId = "zc_nxjc_znc_znf";
        publicData.sceneName = "";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_znc_znf/zc_nxjc_znc_znf_clinker01_mxt.png'); width: 1672px; height: 915px; overflow: hidden;">
        <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5621FT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 289px; left: 242px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1344px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00D5621FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 322px; left: 242px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1344px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C543MCI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 453px; left: 262px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1324px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5561SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 479px; left: 262px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1325px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00D5561SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 506px; left: 262px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1324px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG00C5435ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 476px; left: 67px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1519px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5422ZIS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 513px; left: 67px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1518px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5421ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 626px; left: 91px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1495px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5421ZIS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 662px; left: 91px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1498px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5122PI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 628px; left: 260px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1326px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5022TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 658px; left: 260px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1326px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C530MCI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 732px; left: 401px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1185px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5021TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 591px; left: 16px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1570px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5026TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 152px; left: 717px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 869px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5024TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 76px; left: 858px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 728px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5124PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 100px; left: 858px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 724px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_MEIMOYACHA>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 74px; left: 1027px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 559px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG00C5444ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 156px; left: 844px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 742px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG00C5444ZIS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 187px; left: 844px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 738px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5123PI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 256px; left: 513px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1073px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5023TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 293px; left: 513px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 1073px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C531MSI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 385px; left: 833px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 753px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C532MCI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 419px; left: 833px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 752px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5422ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 481px; left: 706px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 880px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5412ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 511px; left: 816px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 770px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5412ZIS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 539px; left: 816px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 770px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BF00CA403TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 568px; left: 747px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 839px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BGAIBY03>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 600px; left: 650px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 936px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_AO115906>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 623px; left: 650px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 936px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C0CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 682px; left: 722px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 864px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_znc_znf>dcs01_BI00C0CI>DCS'" style="width:81px; display:block; top: 770px; left: 728px; position:absolute; height: 23px;"></div>
<%--        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C0CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 776px; left: 723px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 863px;"></div>--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5411ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 857px; left: 817px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 769px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5411ZIS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 886px; left: 817px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 769px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5025TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 62px; left: 1204px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 382px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG00C5125PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 98px; left: 1204px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 380px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG00C5436ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 53px; left: 1341px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 245px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5425ZIS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 86px; left: 1341px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 240px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BF00C4009TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 195px; left: 1126px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 460px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C533MCI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 234px; left: 1126px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 462px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BO00C545MCI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 173px; left: 1480px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 106px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C529MCI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 202px; left: 1480px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 106px;"></div>
<%--        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG00C5444ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 233px; left: 1480px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 104px;"></div>--%>
    <div class="Conflict"  data-option="id='zc_nxjc_znc_znf>dcs01_BG00C5444ZI>DCS'" style="width:86px; display:block; top: 235px; left: 1480px; position:absolute; height: 19px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00DGD1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 267px; left: 1480px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 102px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5816LI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 491px; left: 976px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 610px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5016TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 524px; left: 976px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 609px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C532MSI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 424px; left: 1189px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 397px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C531MCI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 459px; left: 1189px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 404px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5815LI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 490px; left: 1189px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 397px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5015TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 518px; left: 1189px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 400px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5416ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 541px; left: 1266px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 320px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5416ZIS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 572px; left: 1266px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 316px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG00C5112PI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 643px; left: 1392px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 194px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5615FT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 602px; left: 1538px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 48px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00D5615FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 630px; left: 1538px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 48px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5415ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 707px; left: 1268px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 318px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5415ZIS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 734px; left: 1268px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 316px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG00C5111PI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 732px; left: 1402px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 184px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5616FT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 690px; left: 1539px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 47px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00D5616FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 714px; left: 1539px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 47px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5621>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 798px; left: 1162px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 427px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5615>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 831px; left: 1162px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 424px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5616>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 863px; left: 1162px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 420px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00C5621E>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 799px; left: 1403px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 183px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI00CE>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 86px; display: block; top: 859px; left: 1403px; position: absolute; color: #4cff00; text-align: center; height: 19px; right: 178px;"></div>
        <%--数字量--%>
       <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02A5821RN>BoolSignal" style="position: absolute; top: 188px; left: 190px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_BI02A5821RN_RD,dcs01_BI02A5821RN_RN,dcs01_BI02A5821RN_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02A5822RN>BoolSignal" style="position: absolute; top: 241px; left: 190px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_BI02A5822RN',Display='0:grayC,1:greenCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG01E505MSA>BoolSignal" style="position: absolute; top: 353px; left: 294px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_BG01A505MRD,dcs01_BG01A505MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_MEIMOMSA07>BoolSignal" style="position: absolute; top: 505px; left: 436px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_DI116201,dcs01_DI116202,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_MEIMOMSA08>BoolSignal" style="position: absolute; top: 549px; left: 401px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_DI116201,dcs01_DI116204,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI01EA517SA>BoolSignal" style="position: absolute; top: 649px; left: 499px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_BI01AA517RD,dcs01_BI01AA517RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI01E529MSA>BoolSignal" style="position: absolute; top: 677px; left: 545px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_BI01A529MRD,dcs01_BI01A529MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_MEIMOMSA06>BoolSignal" style="position: absolute; top: 589px; left: 437px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_DI116201,dcs01_DI116203,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG01E503MSA>BoolSignal" style="position: absolute; top: 609px; left: 751px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BG01A503MRD,dcs01_BG01A503MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI011B0SA>BoolSignal" style="position: absolute; top: 714px; left: 751px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI01E529MSA',Display='0:grayC,1:greenCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI01B0SA>BoolSignal" style="position: absolute; top: 807px; left: 751px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI00A0RD,dcs01_BI00A0RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BPQ001SA>BoolSignal" style="position: absolute; top: 683px; left: 836px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_BPQ001RD,dcs01_BPQ001RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02E535MSA>BoolSignal" style="position: absolute; top: 181px; left: 975px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_KYJ02RD,dcs01_KYJ02RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02E536MSA>BoolSignal" style="position: absolute; top: 181px; left: 1014px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI02A536MRD,dcs01_BI02A536MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02E537MSA>BoolSignal" style="position: absolute; top: 181px; left: 1050px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI02A537MRD,dcs01_BI02A537MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02EA552SA>BoolSignal" style="position: absolute; top: 122px; left: 1042px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_DI116315,dcs01_DI116316,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02E533MSA>BoolSignal" style="position: absolute; top: 229px; left: 1087px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI02A533MRD,dcs01_BI02A533MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02A5827RN>BoolSignal" style="position: absolute; top: 307px; left: 1030px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI02A5827RN',Display='0:grayC,1:greenCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02A5828RN>BoolSignal" style="position: absolute; top: 349px; left: 1000px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI02A5828RN',Display='0:grayC,1:greenCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02A5829RN>BoolSignal" style="position: absolute; top: 347px; left: 1053px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI02A5829RN',Display='0:grayC,1:greenCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02E532MSA>BoolSignal" style="position: absolute; top: 377px; left: 931px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI02A532MRD,dcs01_BI02A532MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI02E531MSA>BoolSignal" style="position: absolute; top: 377px; left: 1125px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI02A531MRD,dcs01_BI02A531MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BI01E530MSA>BoolSignal" style="position: absolute; top: 127px; left: 1500px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BI01A530MRD,dcs01_BI01A530MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG01EA541SA1>BoolSignal" style="position: absolute; top: 708px; left: 925px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_BG01AA541RD1,dcs01_BG01AA541RN1,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG01E502MSA>BoolSignal" style="position: absolute; top: 742px; left: 923px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_BG01A502MRD,dcs01_BG01A502MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG01EA542SA1>BoolSignal" style="position: absolute; top: 621px; left: 1122px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_BG01AA542RD1,dcs01_BG01AA542RN1,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BG01E504MSA>BoolSignal" style="position: absolute; top: 658px; left: 1122px; height: 16px; width: 16px;" data-option="RelatedTags='dcs01_BG01A504MRD,dcs01_BG01A504MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div id="zc_nxjc_znc_znf>dcs01_BY113700>DCS" class="TextDisplay" style="position: absolute; top: 453px; left: 505px; color: red; font-size: 14px; text-align: center; height: 14px; width: 73px;">煤磨报警</div>
        <div id="zc_nxjc_znc_znf>dcs01_BY113715>DCS" class="TextDisplay" style="position: absolute; top: 436px; left: 735px; color: red; font-size: 14px; text-align: center; height: 14px; width: 73px;">报警</div>
        <div id="htmlContainer"></div>
    </div>
</body>
</html>
