<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_znc_znf_cementmill01_snxt.aspx.cs" Inherits="Monitor_znc.Web.UI_Monitor.DCSMonitor.zc_nxjc_znc_znf.zc_nxjc_znc_znf_cementmill01_snxt" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

        <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_znc_znf";
        publicData.sceneName = "";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_znc_znf/zc_nxjc_znc_znf_cementmill01_snxt.png'); width: 1675px; height: 915px; overflow: hidden;">
         <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M107_03AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 105px; display: block; top: 93px; left: 212px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1358px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M107_0401AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 105px; display: block; top: 119px; left: 212px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1357px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M107_0402AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 105px; display: block; top: 149px; left: 212px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1359px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M107_04SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 105px; display: block; top: 176px; left: 212px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1359px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M107_04SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 105px; display: block; top: 208px; left: 212px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1358px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_01TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 98px; display: block; top: 46px; left: 438px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1139px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY130706>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 93px; display: block; top: 74px; left: 441px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1141px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_03AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 78px; display: block; top: 101px; left: 457px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1140px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_03SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 70px; display: block; top: 46px; left: 653px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 955px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_03SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 68px; display: block; top: 76px; left: 653px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 956px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133205>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 103px; left: 653px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 955px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M108_01PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 134px; left: 674px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 934px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M108_02PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 132px; left: 860px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 748px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M109SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 103px; left: 993px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 615px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M109AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 94px; left: 1162px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 446px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M109TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 126px; left: 1162px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 443px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 147px; left: 1270px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 338px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 174px; left: 1270px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 334px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M106AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 218px; left: 588px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1020px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M107_1001TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 291px; left: 503px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1105px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M107_1002TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 327px; left: 503px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1108px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M115_0101PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 255px; left: 1011px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 597px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_05SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 291px; left: 904px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 704px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M115_0102PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 257px; left: 1208px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 400px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M116SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 288px; left: 1385px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 223px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M116TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 224px; left: 1551px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 57px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M116AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 254px; left: 1551px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 54px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6216CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 343px; left: 1531px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 77px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_05TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 372px; left: 1014px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 594px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_05AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 398px; left: 1014px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 593px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M102AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 400px; left: 190px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1418px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6211CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 542px; left: 21px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1587px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_DGONG2SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 527px; left: 331px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1277px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133306>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 558px; left: 331px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1277px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY130207>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 604px; left: 311px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1297px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_01PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 655px; left: 291px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1317px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_02GE>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 682px; left: 291px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1319px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133107>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 493px; left: 479px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1129px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_HGONG2SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 536px; left: 532px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1076px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133307>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 565px; left: 532px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1077px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY130206>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 599px; left: 554px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1054px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_02PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 666px; left: 543px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1065px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_01GE>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 693px; left: 543px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1064px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_0101TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 760px; left: 163px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1445px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_0102TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 793px; left: 163px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1443px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_04TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 829px; left: 163px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1441px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_01AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 163px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1444px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_0201TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 758px; left: 409px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1199px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_0202TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 793px; left: 409px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1443px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_06TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 829px; left: 409px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1441px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105_02AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 409px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1444px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C7053TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 781px; left: 595px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1013px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C7052TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 807px; left: 595px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1013px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C7051TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 834px; left: 595px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1013px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_AI12BY7>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 595px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1444px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CJ00C6442ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 51px; display: block; top: 644px; left: 746px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 878px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6012ATI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 51px; display: block; top: 670px; left: 746px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 878px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6012BTI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 51px; display: block; top: 698px; left: 746px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 877px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00ESUM>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 828px; left: 711px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 897px;"></div>
<%--        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6012BTI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 858px; left: 711px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 898px;"></div>--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6611FI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 762px; left: 802px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 806px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00D6611FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 795px; left: 802px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 803px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E001>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 828px; left: 802px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_C6611>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 802px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6612FI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 762px; left: 898px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 710px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00D6612FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 795px; left: 898px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 803px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E002>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 828px; left: 898px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_C6612>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 898px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6613FI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 762px; left: 998px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 610px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00D6613FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 795px; left: 998px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 803px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E003>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 828px; left: 998px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_C6613>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 998px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6614FI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 762px; left: 1086px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 522px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00D6614FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 795px; left: 1086px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 803px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E004>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 828px; left: 1086px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_C6614>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 1086px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6615FI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 762px; left: 1188px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 420px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00D6615FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 795px; left: 1188px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 803px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E005>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 828px; left: 1188px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_C6615>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 1188px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M117_03SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 762px; left: 1295px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 313px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M117_03SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 795px; left: 1295px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 803px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E060>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 828px; left: 1295px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_FHLL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 1295px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CM00C7211CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 762px; left: 1390px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 218px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_AO12BY4>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 795px; left: 1390px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 803px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_TLSG01GD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 828px; left: 1390px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_TLSG01LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 1390px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
         <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133406>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 762px; left: 1487px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 121px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY130204>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 795px; left: 1487px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 803px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_WF1PB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 828px; left: 1487px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_WFBLJ1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 861px; left: 1487px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 800px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00EALL>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 799px; left: 1578px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 30px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133103>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 427px; left: 1184px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 424px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CJ00C6426ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 560px; left: 848px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 760px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_AI12BY1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 560px; left: 948px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 660px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CJ00C6423ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 558px; left: 1034px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 574px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6213CI1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 591px; left: 939px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 669px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6731LD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 621px; left: 958px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 650px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6051TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 484px; left: 1111px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 497px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6113PI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 514px; left: 1111px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 495px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C6224CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 447px; left: 1521px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 87px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C6225CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 487px; left: 1521px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 87px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C6244CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 522px; left: 1521px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 87px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C6245CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 567px; left: 1521px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 82px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6415ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 475px; left: 1360px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 248px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6415ZIS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 510px; left: 1360px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 245px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6115PI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 571px; left: 1313px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 295px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6215CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 67px; display: block; top: 615px; left: 1413px; position: absolute; color: #4cff00; text-align: center; height: 20px; right: 195px;"></div>
          <%--汉字隐藏--%>
        <div id="zc_nxjc_znc_znf>dcs01_M107_08H1>DCS" class="TextDisplay" style="position:absolute; top: 394px; left: 448px; color:red;text-align:center;font-size:14px; height: 16px; width: 117px;">润滑泵油箱上限</div> 
        <div id="zc_nxjc_znc_znf>dcs01_M107_08L1>DCS" class="TextDisplay" style="position:absolute; top: 425px; left: 446px; color:red;text-align:center;font-size:14px; height: 16px; width: 123px;">润滑泵油箱下限</div>
        <div id="zc_nxjc_znc_znf>dcs01_M1110203TTL1>DCS" class="TextDisplay" style="position:absolute; top: 396px; left: 664px; color:red;text-align:center;font-size:13px; height: 16px; width: 123px;">选粉机油站压差高</div>
        <div id="zc_nxjc_znc_znf>dcs01_M1110203TTH1>DCS" class="TextDisplay" style="position:absolute; top: 427px; left: 666px; color:red;text-align:center;font-size:13px; height: 16px; width: 123px;">选粉机油站油温高</div>
        <div id="zc_nxjc_znc_znf>dcs01_M111_0201RD>DCS" class="TextDisplay" style="position:absolute; top: 459px; left: 667px; color:red;text-align:center;font-size:13px; height: 16px; width: 123px;">选粉机油站轻故障</div>
        <div id="zc_nxjc_znc_znf>dcs01_BY131715>DCS" class="TextDisplay" style="position:absolute; top: 489px; left: 668px; color:red;text-align:center;font-size:13px; height: 16px; width: 123px;">选粉机油站压力过低</div>
        <div id="zc_nxjc_znc_znf>dcs01_M1110203PTL1>DCS" class="TextDisplay" style="position:absolute; top: 524px; left: 668px; color:red;text-align:center;font-size:13px; height: 16px; width: 123px;">选粉机油站油位过低</div>
        <div id="zc_nxjc_znc_znf>dcs01_M1110203PTH1>DCS" class="TextDisplay" style="position:absolute; top: 556px; left: 668px; color:red;text-align:center;font-size:13px; height: 16px; width: 123px;">选粉机油站油位高</div>  
        <div id="zc_nxjc_znc_znf>dcs01_SNPBPD001>DCS" class="TextDisplay" style="position:absolute; top: 677px; left: 879px; color:red;text-align:center;font-size:16px; height: 16px; width: 261px;">配比修改错误</div> 
        <%--开关量圆形--%>
 <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M102MSA>BoolSignal" style="position: absolute; top: 429px; left: 210px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M102RD,dcs01_M102RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH02E605MSA>BoolSignal" style="position: absolute; top: 567px; left: 147px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_CH02A605MRD,dcs01_CH02A605MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M101MSA>BoolSignal" style="position: absolute; top: 596px; left: 176px; height: 18px; width: 18px;"data-option="RelatedTags='dcs01_M101RD,dcs01_M101RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
       <%-- <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133901>BoolSignal" style="position: absolute; top: 540px; left: 401px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BY133901,dcs01_BY133902',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>--%>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105MSA01>BoolSignal" style="position: absolute; top: 669px; left: 393px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BY133906,dcs01_BY133907,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105MSA>BoolSignal" style="position: absolute; top: 670px; left: 437px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M105RD,dcs01_M105RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105MSA02>BoolSignal" style="position: absolute; top: 670px; left: 478px; height: 18px; width: 18px;"data-option="RelatedTags='dcs01_BY133908,dcs01_BY133909,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133903>BoolSignal" style="position: absolute; top: 535px; left: 503px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BY133903,dcs01_BY133904',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH01E6651MSA>BoolSignal" style="position: absolute; top: 585px; left: 774px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_CH01A6651MRD,dcs01_CH01A6651MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M1071MSA>BoolSignal" style="position: absolute; top: 330px; left: 465px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M107_01RD,dcs01_M107_01RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M106MSA>BoolSignal" style="position: absolute; top: 256px; left: 626px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M106RD,dcs01_M106RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M114_01MSA>BoolSignal" style="position: absolute; top: 303px; left: 670px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M114_01RD,dcs01_M114_01RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M114_02MSA>BoolSignal" style="position: absolute; top: 304px; left: 717px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M114_02RD,dcs01_M114_02RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M114_03MSA>BoolSignal" style="position: absolute; top: 305px; left: 769px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M114_03RD,dcs01_M114_03RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_0201RN>BoolSignal" style="position: absolute; top: 361px; left: 687px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M111_0201RN',Display='0:grayC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_0202RN>BoolSignal" style="position: absolute; top: 359px; left: 741px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M111_0202RN',Display='0:grayC,1:greenC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_03MSA>BoolSignal" style="position: absolute; top: 328px; left: 861px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M111_03RD,dcs01_M111_03RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111_05MSA>BoolSignal" style="position: absolute; top: 340px; left: 1033px; height: 19px; width: 18px;" data-option="RelatedTags='dcs01_M111_05RD,dcs01_M111_05RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M113MSA>BoolSignal" style="position: absolute; top: 207px; left: 1225px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M113RD,dcs01_M113RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M111MSA>BoolSignal" style="position: absolute; top: 208px; left: 1291px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M111RD,dcs01_M111RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M112MSA>BoolSignal" style="position: absolute; top: 492px; left: 960px; height: 19px; width: 19px;" data-option="RelatedTags='dcs01_M112RD,dcs01_M112RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M114_04MSA>BoolSignal" style="position: absolute; top: 478px; left: 1204px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_BY132910,dcs01_BY132911,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M110MSA>BoolSignal" style="position: absolute; top: 663px; left: 1206px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_M110RD,dcs01_M110RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK01E606MSA>BoolSignal" style="position: absolute; top: 560px; left: 1449px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_CK01A606MRD,dcs01_CK01A606MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK04E602MSA>BoolSignal" style="position: absolute; top: 370px; left: 1471px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_CK04A602MRD,dcs01_CK04A602MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK02E616MSA>BoolSignal" style="position: absolute; top: 638px; left: 1076px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_CK02A616MRD,dcs01_CK02A616MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <%--开关量方形--%>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M208MSA>BoolSignal" style="position: absolute; top: 148px; left: 822px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_M208RD,dcs01_M208RN,0',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M115_01MSA>BoolSignal" style="position: absolute; top: 275px; left: 1156px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_M115_01RD,dcs01_M115_01RN,0',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK01E653MSA>BoolSignal" style="position: absolute; top: 532px; left: 1253px; height: 20px; width: 20px;" data-option="RelatedTags='dcs01_CK01A653MRD,dcs01_CK01A653MRD,0',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div id="htmlContainer"></div>
        </div>
</body>
</html>
