<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_znc_znf_cementmill02_snxt.aspx.cs" Inherits="Monitor_znc.Web.UI_Monitor.DCSMonitor.zc_nxjc_znc_znf.zc_nxjc_znc_znf_cementmill02_snxt" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

        <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_znc_znf";
        publicData.sceneName = "";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_znc_znf/zc_nxjc_znc_znf_cementmill02_snxt.png'); width: 1674px; height: 926px; overflow: hidden;">
        <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M207_03AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 62px; left: 322px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M207_0401AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 88px; left: 322px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M207_0402AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 115px; left: 322px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M207_04SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 146px; left: 321px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M207_04SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 177px; left: 320px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211_01TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 65px; left: 533px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY131007>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 90px; left: 532px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211_03AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 118px; left: 532px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211_03SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 142px; left: 532px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211_03SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 166px; left: 532px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133206>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 190px; left: 532px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M106AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 232px; left: 585px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M208_02PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 201px; left: 666px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M208_01PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 203px; left: 860px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M209SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 169px; left: 908px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M209TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 146px; left: 995px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M209AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 170px; left: 995px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 185px; left: 1215px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 211px; left: 1215px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M214_01AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 239px; left: 1300px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M215_0101PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 267px; left: 994px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY124004>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 292px; left: 993px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY130305>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 314px; left: 994px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211_05TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 374px; left: 993px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211_05AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 400px; left: 994px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M215_0102PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 269px; left: 1163px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M216TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 324px; left: 1352px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M216AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 347px; left: 1352px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CJ00C6236CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 387px; left: 1449px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6231CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 438px; left: 34px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M202AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 357px; left: 153px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M207_1001TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 322px; left: 507px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M207_1002TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 350px; left: 507px; position:absolute;color:#4cff00;text-align:right; height: 21px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133106>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 505px; left: 474px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_DGONG1SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 544px; left: 266px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133304>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 573px; left: 267px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_HGONG1SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 546px; left: 508px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133305>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 575px; left: 509px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY130300>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 623px; left: 263px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY130301>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 626px; left: 510px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133207>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 669px; left: 267px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_02GE>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 693px; left: 267px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_01PT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 667px; left: 527px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_01GE>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 691px; left: 527px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133104>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 460px; left: 934px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6054TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 506px; left: 1026px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6133PI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 529px; left: 1026px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6031TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 563px; left: 842px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6032TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 564px; left: 947px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6233CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 596px; left: 956px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6711LD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 622px; left: 956px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6435ZI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 475px; left: 1319px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6435ZIS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 499px; left: 1319px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6115PI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 556px; left: 1269px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6235CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 575px; left: 1375px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6035TI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 597px; left: 1376px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6135PI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 621px; left: 1377px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C6224CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 504px; left: 1523px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C6225CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 543px; left: 1523px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C6244CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 586px; left: 1526px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CL00C6245CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 627px; left: 1525px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6032DTI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:69px; display:block; top: 642px; left: 728px; position:absolute;color:#4cff00;text-align:right; height: 17px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6032CTI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:69px; display:block; top: 663px; left: 727px; position:absolute;color:#4cff00;text-align:right; height: 17px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6032ATI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:69px; display:block; top: 683px; left: 728px; position:absolute;color:#4cff00;text-align:right; height: 17px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK00C6032BTI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:69px; display:block; top: 703px; left: 728px; position:absolute;color:#4cff00;text-align:right; height: 17px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_0101TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 763px; left: 159px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_0102TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 796px; left: 159px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_04TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 833px; left: 159px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_01AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:83px; display:block; top: 863px; left: 158px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_0201TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:72px; display:block; top: 762px; left: 407px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_0202TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:78px; display:block; top: 794px; left: 401px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_06TT>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 830px; left: 402px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M205_02AI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 863px; left: 403px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_AI12BY10>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:72px; display:block; top: 786px; left: 597px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_AI12BY9>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:78px; display:block; top: 810px; left: 591px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_AI12BY8>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:75px; display:block; top: 835px; left: 594px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_AI12BY11>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 863px; left: 596px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6631FI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 767px; left: 799px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6632FI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 765px; left: 895px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6633FI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 766px; left: 992px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6634FI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 767px; left: 1086px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00C6635FI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 765px; left: 1179px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M217_03SI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 767px; left: 1291px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CM00C7231CI>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 767px; left: 1393px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133403>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 765px; left: 1487px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00D6631FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 800px; left: 799px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00D6632FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 801px; left: 895px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00D6633FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 799px; left: 992px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00D6634FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 799px; left: 1088px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00D6635FC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 799px; left: 1178px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_M217_03SC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 798px; left: 1286px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_AO12BY5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 799px; left: 1393px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY130205>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 799px; left: 1488px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E006>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 834px; left: 801px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E007>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 833px; left: 895px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E008>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 833px; left: 992px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E009>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 832px; left: 1090px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E010>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 831px; left: 1179px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00E070>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 832px; left: 1288px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_TLSG02GD>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 832px; left: 1393px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_WF2PB>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 830px; left: 1489px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_C6631>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 863px; left: 800px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_C6632>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 865px; left: 894px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_C6633>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 865px; left: 993px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_C6634>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 864px; left: 1088px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_C6635>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 863px; left: 1180px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_FHLLS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 862px; left: 1291px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_TLSG02LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 864px; left: 1393px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_WFBLJ2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 864px; left: 1489px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00ESUM2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 831px; left: 703px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH00EALL2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:73px; display:block; top: 810px; left: 1574px; position:absolute;color:#4cff00;text-align:right; height: 21px; margin-bottom: 0px;"></div>

        <%--开关量--%>
          <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH03E635MSA>BoolSignal" style="position: absolute; top: 464px; left: 148px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_CK07A646MRN,dcs01_CH03FGUK,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M201MSA>BoolSignal" style="position: absolute; top: 500px; left: 167px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M201RD,dcs01_M201RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M2071MSA>BoolSignal" style="position: absolute; top: 342px; left: 467px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M207_01RD,dcs01_M207_01RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133811>BoolSignal" style="position: absolute; top: 559px; left: 359px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BY133811,dcs01_BY133812',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_BY133813>BoolSignal" style="position: absolute; top: 557px; left: 484px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BY133813,dcs01_BY133814,0',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105MSA01>BoolSignal" style="position: absolute; top: 681px; left: 386px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BY133906,dcs01_BY133907,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105MSA>BoolSignal" style="position: absolute; top: 680px; left: 436px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M105RD,dcs01_M105RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M105MSA02>BoolSignal" style="position: absolute; top: 680px; left: 480px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BY133908,dcs01_BY133909,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M214_01MSA>BoolSignal" style="position: absolute; top: 308px; left: 673px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M214_01RD,dcs01_M214_01RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M214_02MSA>BoolSignal" style="position: absolute; top: 307px; left: 721px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M214_02RD,dcs01_M214_02RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M214_03MSA>BoolSignal" style="position: absolute; top: 306px; left: 771px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M214_03RD,dcs01_M214_03RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211_0201RN>BoolSignal" style="position: absolute; top: 362px; left: 686px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M211_0201RN',Display='0:grayC,1:greenCB'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211_0202RN>BoolSignal" style="position: absolute; top: 362px; left: 740px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M211_0202RN',Display='0:grayC,1:greenCB'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M208MSA>BoolSignal" style="position: absolute; top: 219px; left: 829px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M208MSA',Display='0:grayS,1:greenSB'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M215_01MSA>BoolSignal" style="position: absolute; top: 283px; left: 1153px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M215_01RD,dcs01_M215_01RN,0',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK06E670MSA>BoolSignal" style="position: absolute; top: 527px; left: 1163px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_CK06A670MRD,dcs01_CK06A670MRN,0',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211_03MSA>BoolSignal" style="position: absolute; top: 334px; left: 864px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M211_03RD,dcs01_M211_03RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M211_05MSA>BoolSignal" style="position: absolute; top: 344px; left: 1035px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M211_05RD,dcs01_M211_05RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M212MSA>BoolSignal" style="position: absolute; top: 515px; left: 936px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M212RD,dcs01_M212RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M214_04MSA>BoolSignal" style="position: absolute; top: 514px; left: 983px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_BY132912,dcs01_BY132913,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CH01E6652MSA>BoolSignal" style="position: absolute; top: 591px; left: 773px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_CH01A6652MRD,dcs01_CH01A6652MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK07E646MSA>BoolSignal" style="position: absolute; top: 655px; left: 1069px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_CK07A646MRD,dcs01_CK07A646MRN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_M210MSA>BoolSignal" style="position: absolute; top: 695px; left: 1128px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_M210RD,dcs01_M210RN,0',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
         <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs01_CK06E636MSA>BoolSignal" style="position: absolute; top: 544px; left: 1424px; height: 18px; width: 18px;" data-option="RelatedTags='dcs01_CK06A636MRD,dcs01_CK06A636MRN',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>


        <%--汉子隐藏--%>
        <div id="zc_nxjc_znc_znf>dcs01_M207_08H1>DCS" class="TextDisplay" style="position:absolute; top: 410px; left: 451px; color:red;text-align:center;font-size:13px">润滑泵油箱上限</div>  
        <div id="zc_nxjc_znc_znf>dcs01_M207_08L1>DCS" class="TextDisplay" style="position:absolute; top: 433px; left: 451px; color:red;text-align:center;font-size:13px">润滑泵油箱下限</div>  
        <div id="zc_nxjc_znc_znf>dcs01_M2110203TTL1>DCS" class="TextDisplay" style="position:absolute; top: 405px; left: 671px; color:red;text-align:center;font-size:13px">选粉机油站压差高</div>  
        <div id="zc_nxjc_znc_znf>dcs01_M2110203TTH1>DCS" class="TextDisplay" style="position:absolute; top: 421px; left: 671px; color:red;text-align:center;font-size:13px">选粉机油站油温高</div> 
        <div id="zc_nxjc_znc_znf>dcs01_M211_0201RD>DCS" class="TextDisplay" style="position:absolute; top: 437px; left: 672px; color:red;text-align:center;font-size:13px">选粉机油站轻故障</div> 
        <div id="zc_nxjc_znc_znf>dcs01_BY132715>DCS" class="TextDisplay" style="position:absolute; top: 453px; left: 671px; color:red;text-align:center;font-size:13px">选粉机油站压力过低</div> 
        <div id="zc_nxjc_znc_znf>dcs01_M2110203PTL1>DCS" class="TextDisplay" style="position:absolute; top: 471px; left: 671px; color:red;text-align:center;font-size:13px">选粉机油站油位低</div> 
        <div id="zc_nxjc_znc_znf>dcs01_M2110203PTH1>DCS" class="TextDisplay" style="position:absolute; top: 487px; left: 671px; color:red;text-align:center;font-size:13px">选粉机油站油位高</div> 
        <div id="zc_nxjc_znc_znf>dcs01_SNPBPD001>DCS" class="TextDisplay" style="position:absolute; top: 702px; left: 871px; color:red;text-align:center;font-size:17px; height: 19px; width: 139px;">配比修改错误</div> 
  



        <div id="htmlContainer"></div>
        </div>
</body>
</html>