<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_znc_znf_clinker02_yt.aspx.cs" Inherits="Monitor_znc.Web.UI_Monitor.DCSMonitor.zc_nxjc_znc_znf.zc_nxjc_znc_znf_clinker02_yt" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

        <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_znc_znf";
        publicData.sceneName = "";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_znc_znf/zc_nxjc_znc_znf_clinker02_yt.png'); width: 1652px; height: 890px; overflow: hidden;">

  <%--模拟量--%>
       <div class="AnlogSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C5701T1>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 70px; display: block; top: 81px; left: 188px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 1394px;"></div>    
       <div class="AnlogSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C5701P1>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 70px; display: block; top: 109px; left: 188px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1394px;"></div>     
       <div class="AnlogSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C5702T1>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 66px; display: block; top: 195px; left: 175px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 1412px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_C5702T2>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 216px; left: 175px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 1412px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_C5702T3>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 237px; left: 175px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 1412px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_C5702T4>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 257px; left: 175px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 1412px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_C5724P1>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 94px; left: 407px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 1180px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_C5725I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 71px; left: 613px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 974px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_C5724I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 123px; left: 616px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 971px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_CAIBY18>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 75px; left: 698px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 889px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_CAOBY1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 96px; left: 698px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 889px;background:blue;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_DI125508>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 197px; left: 424px; position: absolute; color: #4cff00; text-align: center; height: 18px; right: 1163px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_AI1252021>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 215px; left: 424px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1162px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_DI125509>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 233px; left: 424px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1163px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_AI1252022>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 251px; left: 424px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1164px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_DI125510>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 269px; left: 424px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1162px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_AI1252023>DCS"   data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 285px; left: 424px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1163px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_DI125511>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 194px; left: 541px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1046px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_AI1252024>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 211px; left: 541px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1046px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_DI125512>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 228px; left: 541px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1045px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_AI1252025>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 245px; left: 541px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1045px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_DI125513>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 262px; left: 541px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1045px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_AI1252026>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 279px; left: 541px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 1044px;"></div>
       <div class="AnlogSignal mchart"   id ="zc_nxjc_znc_znf>dcs02_AI125301>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 196px; left: 655px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 932px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_AI125302>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 215px; left: 655px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 933px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_AI125303>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 232px; left: 655px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 932px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_DI125501>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 250px; left: 635px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 952px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_DI125514>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 265px; left: 635px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 951px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_DI125504>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 282px; left: 635px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 952px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_AI125201>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 203px; left: 758px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 829px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_AO125001>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 222px; left: 758px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 829px;background:blue;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_DI125502>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 250px; left: 728px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 859px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_DI125515>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 270px; left: 728px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 858px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_DI125503>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 249px; left: 810px; position: absolute; color: #4cff00; text-align: center; height: 17px; right: 777px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_DI125516>DCS"  data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 270px; left: 810px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 778px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_CAIBY1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 135px; left: 846px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 741px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5719T3>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 115px; left: 846px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 741px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5712V1SP>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 54px; left: 932px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 655px;background:blue;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5712V1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 33px; left: 932px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 655px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5715T1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 135px; left: 1009px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 578px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5715P1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 156px; left: 1009px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 578px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C57151I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 100px; left: 1018px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 569px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C57151U1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 79px; left: 1018px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 569px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_CAOBY4>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 59px; left: 1018px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 569px;background:blue;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_CAOBY5>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 58px; left: 1137px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 450px;background:blue;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C57152U1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 75px; left: 1137px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 450px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C57152I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 94px; left: 1137px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 450px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_CAOBY6>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 58px; left: 1236px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 351px;background:blue;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C57153U1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 74px; left: 1236px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 350px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C57153I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 91px; left: 1236px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 349px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5715T2>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 136px; left: 1261px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 326px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5715P2>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 159px; left: 1261px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 326px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5718V1SP>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 115px; left: 1405px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 182px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5718V1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 95px; left: 1405px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 182px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5719I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 120px; left: 1523px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 64px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5719T>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 100px; left: 1523px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 64px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5702BI1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 252px; left: 967px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 620px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5702T5>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 270px; left: 967px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 621px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C6601I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 420px; left: 1187px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 400px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_CAIBY011>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 526px; left: 1440px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 147px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C6600L1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 676px; left: 1340px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 247px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C6600L3>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 65px; display: block; top: 673px; left: 1503px;  position: absolute; color: #4cff00; text-align: center; height: 17px; right: 84px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5703V1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 621px; left: 69px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1498px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5703V1SP>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 647px; left: 69px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1498px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5703I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 674px; left: 69px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1498px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5703T1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 697px; left: 69px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1498px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5703P1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 721px; left: 69px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1498px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5703F1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 745px; left: 69px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1500px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5707V1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 621px; left: 176px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1391px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5707V1SP>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 649px; left: 176px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1392px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_AI125306>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 672px; left: 176px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1391px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5704T1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 698px; left: 176px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1390px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5704P1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 722px; left: 176px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1392px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5704F1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 744px; left: 176px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1392px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5708V1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 621px; left: 280px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1287px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5708V1SP>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 646px; left: 280px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1285px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5705I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 674px; left: 280px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1287px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5705T1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 696px; left: 280px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1287px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5705P1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 722px; left: 280px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1287px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5705F1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 745px; left: 280px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1287px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5709V1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 620px; left: 382px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1185px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5709V1SP>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 646px; left: 382px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1184px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5706I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 672px; left: 382px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1183px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5706T1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 697px; left: 382px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1181px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5706P1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 719px; left: 382px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1181px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5706F1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 744px; left: 382px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1181px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5710V1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 620px; left: 487px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1080px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5710V1SP>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 649px; left: 487px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1082px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5707I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 674px; left: 487px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1081px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5707T1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 697px; left: 487px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1081px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5707P1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 721px; left: 487px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1080px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5707F1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 744px; left: 487px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 1080px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_V6FJAI>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 620px; left: 591px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 976px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_V6FJAO>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 647px; left: 591px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 975px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5708I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 671px; left: 591px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 975px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5708T1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 698px; left: 591px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 975px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5708P1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 722px; left: 591px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 976px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5708F1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 746px; left: 591px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 975px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_V7FJAI>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 620px; left: 694px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 873px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_V7FJAO>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 646px; left: 694px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 872px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5709I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 670px; left: 694px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 870px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5709T1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 697px; left: 694px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 872px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5709P1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 721px; left: 694px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 872px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5709F1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 745px; left: 694px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 870px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_V8FJAI>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 620px; left: 801px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 766px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_V8FJAO>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 644px; left: 801px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 766px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5710I1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 670px; left: 801px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 763px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5710T1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 696px; left: 801px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 763px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5710P1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 720px; left: 801px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 763px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C5710F1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 744px; left: 801px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 763px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_GYDY>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 814px; left: 626px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 941px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_CAIBY15>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 817px; left: 854px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 713px;"></div>
       <div class="AnlogSignal mchart"    id ="zc_nxjc_znc_znf>dcs02_C6604A1>DCS"    data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 85px; display: block; top: 849px; left: 778px;  position: absolute; color: #4cff00; text-align: center; height: 20px; right: 789px;"></div>


        <%--开关量--%>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C5730R>BoolSignal"    style ="position: absolute; top: 413px; left: 73px; height: 22px; width: 22px;"   data-option="RelatedTags='dcs02_C5730R,dcs02_C5730A1',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_znc_znf>dcs02_C5730R>BoolSignal'"style="position: absolute; top: 413px; left: 110px; height: 22px; width: 22px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_znc_znf>dcs02_C5730R>BoolSignal'"style="position: absolute; top: 413px; left: 149px; height: 22px; width: 22px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_znc_znf>dcs02_C5730R>BoolSignal'"style="position: absolute; top: 413px; left: 182px; height: 22px; width: 22px;"></div>
 
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C57V01R>BoolSignal"   style="position: absolute; top: 17px; left: 579px; height: 23px; width: 23px;"   data-option="RelatedTags='dcs02_C57V01R,dcs02_C57V01A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C5725R>BoolSignal"   style="position: absolute; top: 67px; left: 579px; height: 23px; width: 23px;"   data-option="RelatedTags='dcs02_C5725R,dcs02_C5725A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C5724R>BoolSignal"   style="position: absolute; top: 118px; left: 580px; height: 23px; width: 23px;"   data-option="RelatedTags='dcs02_C5724R,dcs02_C5724A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C5702BR>BoolSignal"   style="position: absolute; top: 259px; left: 891px; height: 20px; width: 20px;"   data-option="RelatedTags='dcs02_C5702BR,dcs02_C5702BA',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C5715R>BoolSignal"   style="position: absolute; top: 114px; left: 1166px; height: 20px; width: 20px;"   data-option="RelatedTags='dcs02_C5715R,dcs02_C5715C',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C57151R>BoolSignal"  style="position: absolute; top: 164px; left: 1135px; height: 20px; width: 20px;"   data-option="RelatedTags='dcs02_C57151R,dcs02_C57151A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C57152R>BoolSignal"   style="position: absolute; top: 164px; left: 1166px; height: 20px; width: 20px;"   data-option="RelatedTags='dcs02_C57152R,dcs02_C57152A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C57153R>BoolSignal"  style="position: absolute; top: 163px; left: 1198px; height: 20px; width: 20px;"  data-option="RelatedTags='dcs02_C57153R,dcs02_C57153A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C5719R>BoolSignal"   style="position: absolute; top: 148px; left: 1532px; height: 22px; width: 22px;"  data-option="RelatedTags='dcs02_C5719R,dcs02_C5719A2',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_znc_znf>dcs02_C5715EA>BoolSignal"   style="position: absolute; top: 247px; left: 1252px; height: 15px; width: 20px;"  data-option="RelatedTags='dcs02_C5715EA,dcs02_C5715EAL',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart"    id="zc_nxjc_znc_znf>dcs02_C5715FA>BoolSignal"   style="position: absolute; top: 299px; left: 1204px; height: 15px; width: 20px;"  data-option="RelatedTags='dcs02_C5715FA,dcs02_C5715FAL',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart"    id="zc_nxjc_znc_znf>dcs02_C5715GA>BoolSignal"   style="position: absolute; top: 339px; left: 1212px; height: 18px; width: 18px;"  data-option="RelatedTags='dcs02_C5715GA,dcs02_C5715GAL',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart"    id="zc_nxjc_znc_znf>dcs02_C5715HR>BoolSignal"   style="position: absolute; top: 338px; left: 1263px; height: 18px; width: 18px;"  data-option="RelatedTags='dcs02_C5715HR,dcs02_C5715HA',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart"    id="zc_nxjc_znc_znf>dcs02_C5728R>BoolSignal"   style="position: absolute; top: 376px; left: 1117px; height: 15px; width: 18px;"  data-option="RelatedTags='dcs02_C5728R,dcs02_C5728A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart"    id="zc_nxjc_znc_znf>dcs02_C6601R>BoolSignal"   style="position: absolute; top: 452px; left: 1325px; height: 15px; width: 18px;"  data-option="RelatedTags='dcs02_C6601R,dcs02_C6601A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart"    id="zc_nxjc_znc_znf>dcs02_C6608R>BoolSignal"   style="position: absolute; top: 397px; left: 1380px; height: 20px; width: 20px;"  data-option="RelatedTags='dcs02_C6608R,dcs02_C6608A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart"    id="zc_nxjc_znc_znf>dcs02_C6606R>BoolSignal"   style="position: absolute; top: 380px; left: 1458px; height: 20px; width: 20px;"  data-option="RelatedTags='dcs02_C6606R,dcs02_C6606A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart"    id="zc_nxjc_znc_znf>dcs02_C6606AR>BoolSignal"   style="position: absolute; top: 475px; left: 1458px; height: 20px; width: 20px;"  data-option="RelatedTags='dcs02_C6606AR,dcs02_C6606AA',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart"    id="zc_nxjc_znc_znf>dcs02_C6602R>BoolSignal"   style="position: absolute; top: 559px; left: 1575px; height: 15px; width: 20px;"  data-option="RelatedTags='dcs02_C6602R,dcs02_C6602A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
        <div class="BoolSignal mchart"    id="zc_nxjc_znc_znf>dcs02_C6603A1>BoolSignal"   style="position: absolute; top: 597px; left: 1301px; height: 18px; width: 18px;"  data-option="RelatedTags='dcs02_C6603A1,dcs02_C6603A2',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C6604A1>BoolSignal"   style="position: absolute; top: 597px; left: 1427px; height: 18px; width: 18px;"  data-option="RelatedTags='dcs02_C6604A1,dcs02_C6604A2',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C6605A1>BoolSignal"   style="position: absolute; top: 598px; left: 1511px; height: 18px; width: 18px;"  data-option="RelatedTags='dcs02_C6605A1,dcs02_C6605A2',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C6600L2>BoolSignal"   style="position: absolute; top: 648px; left: 1363px; height: 18px; width: 18px;"  data-option="RelatedTags='dcs02_C6600L2',Display='0:grayC,1:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C6600L4>BoolSignal"    style="position: absolute; top: 646px; left: 1525px; height: 18px; width: 18px;"  data-option="RelatedTags='dcs02_C6600L4',Display='0:grayC,1:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C5710R>BoolSignal"   style="position: absolute; top: 497px; left: 735px; height: 17px; width: 17px;"  data-option="RelatedTags='dcs02_C5710R,dcs02_C5710A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C5709R>BoolSignal"    style="position: absolute; top: 496px; left: 663px; height: 17px; width: 17px;"  data-option="RelatedTags='dcs02_C5709R,dcs02_C5709A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_CDIBY2>BoolSignal"    style="position: absolute; top: 497px; left: 589px; height: 17px; width: 17px;"  data-option="RelatedTags='dcs02_CDIBY2,dcs02_C5708A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C5707R>BoolSignal"    style="position: absolute; top: 496px; left: 516px; height: 17px; width: 17px;"  data-option="RelatedTags='dcs02_C5707R,dcs02_C5707A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C5706R>BoolSignal"    style="position: absolute; top: 496px; left: 441px; height: 17px; width: 17px;"  data-option="RelatedTags='dcs02_C5706R,dcs02_C5706A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C5705R>BoolSignal"    style="position: absolute; top: 495px; left: 365px; height: 17px; width: 17px;"  data-option="RelatedTags='dcs02_C5705R,dcs02_C5705A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C5704R>BoolSignal"    style="position: absolute; top: 495px; left: 297px; height: 17px; width: 17px;"  data-option="RelatedTags='dcs02_C5704R,dcs02_C5704A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C5703R>BoolSignal"    style="position: absolute; top: 495px; left: 221px; height: 17px; width: 17px;"  data-option="RelatedTags='dcs02_C5703R,dcs02_C5703A',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>
         <div   id ="zc_nxjc_qtx_tys>dcs01_T33020AR_FL>DCS" class="TextDisplay" style="position:absolute; top: 853px; left: 651px; color:black;font-size:12px;text-align:center; height: 14px; width: 73px;">爬坡机电铃</div>  
         <div class="BoolSignal mchart"   id="zc_nxjc_znc_znf>dcs02_C6604MO2>BoolSignal"    style="position: absolute; top: 851px; left: 642px; height: 17px; width: 91px;"  data-option="RelatedTags='dcs02_C6604MO2,dcs02_C6604C2',Display='00:grayC,01:redCB,10:greenC,11:redCB'"></div>










        <div id="htmlContainer"></div>
        </div>
</body>
</html>