//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor_shell.Service.ServiceReference_RealTimeTagValue {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDecimal", Namespace="http://tempuri.org/", ItemName="decimal")]
    [System.SerializableAttribute()]
    public class ArrayOfDecimal : System.Collections.Generic.List<decimal> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfBoolean", Namespace="http://tempuri.org/", ItemName="boolean")]
    [System.SerializableAttribute()]
    public class ArrayOfBoolean : System.Collections.Generic.List<bool> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalDataGroup_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DigitalDataGroup_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Monitor_shell.Service.ServiceReference_RealTimeTagValue.DigitalDataItem_Serialization[] DataSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationIdField, value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.DigitalDataItem_Serialization[] DataSet {
            get {
                return this.DataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSetField, value) != true)) {
                    this.DataSetField = value;
                    this.RaisePropertyChanged("DataSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalDataItem_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DigitalDataItem_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        private bool ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalogDataGroup_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AnalogDataGroup_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Monitor_shell.Service.ServiceReference_RealTimeTagValue.AnalogDataItem_Serialization[] DataSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationIdField, value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.AnalogDataItem_Serialization[] DataSet {
            get {
                return this.DataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSetField, value) != true)) {
                    this.DataSetField = value;
                    this.RaisePropertyChanged("DataSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalogDataItem_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AnalogDataItem_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        private decimal ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectDataGroup_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ObjectDataGroup_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Monitor_shell.Service.ServiceReference_RealTimeTagValue.ObjectDataItem_Serialization[] DataSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationIdField, value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.ObjectDataItem_Serialization[] DataSet {
            get {
                return this.DataSetField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSetField, value) != true)) {
                    this.DataSetField = value;
                    this.RaisePropertyChanged("DataSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectDataItem_Serialization", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfDecimal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfBoolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.DigitalDataGroup_Serialization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.DigitalDataItem_Serialization[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.DigitalDataItem_Serialization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.AnalogDataGroup_Serialization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.AnalogDataItem_Serialization[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.AnalogDataItem_Serialization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.ObjectDataGroup_Serialization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor_shell.Service.ServiceReference_RealTimeTagValue.ObjectDataItem_Serialization[]))]
    public partial class ObjectDataItem_Serialization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_RealTimeTagValue.RealTimeDataSoap")]
    public interface RealTimeDataSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldResponse HelloWorld(Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAnalogData", ReplyAction="*")]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataResponse SetAnalogData(Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetDigitalData", ReplyAction="*")]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataResponse SetDigitalData(Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDigitalDataA", ReplyAction="*")]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataAResponse GetDigitalDataA(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataARequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAnalogDataA", ReplyAction="*")]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataAResponse GetAnalogDataA(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataARequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjectDataA", ReplyAction="*")]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataAResponse GetObjectDataA(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataARequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDigitalDataS", ReplyAction="*")]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSResponse GetDigitalDataS(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 myOrganizationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAnalogDataS", ReplyAction="*")]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSResponse GetAnalogDataS(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAnalogDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAnalogData", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataRequestBody Body;
        
        public SetAnalogDataRequest() {
        }
        
        public SetAnalogDataRequest(Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetAnalogDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfDecimal myTagValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string myKeyword;
        
        public SetAnalogDataRequestBody() {
        }
        
        public SetAnalogDataRequestBody(string myOrganizationId, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfDecimal myTagValue, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myTagValue = myTagValue;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetAnalogDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetAnalogDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataResponseBody Body;
        
        public SetAnalogDataResponse() {
        }
        
        public SetAnalogDataResponse(Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetAnalogDataResponseBody {
        
        public SetAnalogDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDigitalDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDigitalData", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataRequestBody Body;
        
        public SetDigitalDataRequest() {
        }
        
        public SetDigitalDataRequest(Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDigitalDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfBoolean myTagValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string myKeyword;
        
        public SetDigitalDataRequestBody() {
        }
        
        public SetDigitalDataRequestBody(string myOrganizationId, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfBoolean myTagValue, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myTagValue = myTagValue;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDigitalDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDigitalDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataResponseBody Body;
        
        public SetDigitalDataResponse() {
        }
        
        public SetDigitalDataResponse(Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetDigitalDataResponseBody {
        
        public SetDigitalDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDigitalDataARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDigitalDataA", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataARequestBody Body;
        
        public GetDigitalDataARequest() {
        }
        
        public GetDigitalDataARequest(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDigitalDataARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string myKeyword;
        
        public GetDigitalDataARequestBody() {
        }
        
        public GetDigitalDataARequestBody(string myOrganizationId, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDigitalDataAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDigitalDataAResponse", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataAResponseBody Body;
        
        public GetDigitalDataAResponse() {
        }
        
        public GetDigitalDataAResponse(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDigitalDataAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.DigitalDataGroup_Serialization GetDigitalDataAResult;
        
        public GetDigitalDataAResponseBody() {
        }
        
        public GetDigitalDataAResponseBody(Monitor_shell.Service.ServiceReference_RealTimeTagValue.DigitalDataGroup_Serialization GetDigitalDataAResult) {
            this.GetDigitalDataAResult = GetDigitalDataAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnalogDataARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnalogDataA", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataARequestBody Body;
        
        public GetAnalogDataARequest() {
        }
        
        public GetAnalogDataARequest(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnalogDataARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string myKeyword;
        
        public GetAnalogDataARequestBody() {
        }
        
        public GetAnalogDataARequestBody(string myOrganizationId, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnalogDataAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnalogDataAResponse", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataAResponseBody Body;
        
        public GetAnalogDataAResponse() {
        }
        
        public GetAnalogDataAResponse(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnalogDataAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.AnalogDataGroup_Serialization GetAnalogDataAResult;
        
        public GetAnalogDataAResponseBody() {
        }
        
        public GetAnalogDataAResponseBody(Monitor_shell.Service.ServiceReference_RealTimeTagValue.AnalogDataGroup_Serialization GetAnalogDataAResult) {
            this.GetAnalogDataAResult = GetAnalogDataAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectDataARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectDataA", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataARequestBody Body;
        
        public GetObjectDataARequest() {
        }
        
        public GetObjectDataARequest(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetObjectDataARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string myKeyword;
        
        public GetObjectDataARequestBody() {
        }
        
        public GetObjectDataARequestBody(string myOrganizationId, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectDataAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectDataAResponse", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataAResponseBody Body;
        
        public GetObjectDataAResponse() {
        }
        
        public GetObjectDataAResponse(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetObjectDataAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.ObjectDataGroup_Serialization GetObjectDataAResult;
        
        public GetObjectDataAResponseBody() {
        }
        
        public GetObjectDataAResponseBody(Monitor_shell.Service.ServiceReference_RealTimeTagValue.ObjectDataGroup_Serialization GetObjectDataAResult) {
            this.GetObjectDataAResult = GetObjectDataAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDigitalDataSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDigitalDataS", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSRequestBody Body;
        
        public GetDigitalDataSRequest() {
        }
        
        public GetDigitalDataSRequest(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDigitalDataSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string myKeyword;
        
        public GetDigitalDataSRequestBody() {
        }
        
        public GetDigitalDataSRequestBody(string myOrganizationId, string myTagName, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDigitalDataSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDigitalDataSResponse", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSResponseBody Body;
        
        public GetDigitalDataSResponse() {
        }
        
        public GetDigitalDataSResponse(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDigitalDataSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDigitalDataSResult;
        
        public GetDigitalDataSResponseBody() {
        }
        
        public GetDigitalDataSResponseBody(string GetDigitalDataSResult) {
            this.GetDigitalDataSResult = GetDigitalDataSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnalogDataSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnalogDataS", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSRequestBody Body;
        
        public GetAnalogDataSRequest() {
        }
        
        public GetAnalogDataSRequest(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnalogDataSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string myOrganizationId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string myTagName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string myKeyword;
        
        public GetAnalogDataSRequestBody() {
        }
        
        public GetAnalogDataSRequestBody(string myOrganizationId, string myTagName, string myKeyword) {
            this.myOrganizationId = myOrganizationId;
            this.myTagName = myTagName;
            this.myKeyword = myKeyword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAnalogDataSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAnalogDataSResponse", Namespace="http://tempuri.org/", Order=0)]
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSResponseBody Body;
        
        public GetAnalogDataSResponse() {
        }
        
        public GetAnalogDataSResponse(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAnalogDataSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAnalogDataSResult;
        
        public GetAnalogDataSResponseBody() {
        }
        
        public GetAnalogDataSResponseBody(string GetAnalogDataSResult) {
            this.GetAnalogDataSResult = GetAnalogDataSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RealTimeDataSoapChannel : Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeDataSoapClient : System.ServiceModel.ClientBase<Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap>, Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap {
        
        public RealTimeDataSoapClient() {
        }
        
        public RealTimeDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldResponse Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap.HelloWorld(Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldRequest inValue = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldRequest();
            inValue.Body = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldRequestBody();
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.HelloWorldResponse retVal = ((Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataResponse Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap.SetAnalogData(Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataRequest request) {
            return base.Channel.SetAnalogData(request);
        }
        
        public void SetAnalogData(string myOrganizationId, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfDecimal myTagValue, string myKeyword) {
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataRequest inValue = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataRequest();
            inValue.Body = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myTagValue = myTagValue;
            inValue.Body.myKeyword = myKeyword;
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetAnalogDataResponse retVal = ((Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap)(this)).SetAnalogData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataResponse Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap.SetDigitalData(Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataRequest request) {
            return base.Channel.SetDigitalData(request);
        }
        
        public void SetDigitalData(string myOrganizationId, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfBoolean myTagValue, string myKeyword) {
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataRequest inValue = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataRequest();
            inValue.Body = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myTagValue = myTagValue;
            inValue.Body.myKeyword = myKeyword;
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.SetDigitalDataResponse retVal = ((Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap)(this)).SetDigitalData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataAResponse Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap.GetDigitalDataA(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataARequest request) {
            return base.Channel.GetDigitalDataA(request);
        }
        
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.DigitalDataGroup_Serialization GetDigitalDataA(string myOrganizationId, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName, string myKeyword) {
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataARequest inValue = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataARequest();
            inValue.Body = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataARequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myKeyword = myKeyword;
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataAResponse retVal = ((Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap)(this)).GetDigitalDataA(inValue);
            return retVal.Body.GetDigitalDataAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataAResponse Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap.GetAnalogDataA(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataARequest request) {
            return base.Channel.GetAnalogDataA(request);
        }
        
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.AnalogDataGroup_Serialization GetAnalogDataA(string myOrganizationId, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName, string myKeyword) {
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataARequest inValue = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataARequest();
            inValue.Body = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataARequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myKeyword = myKeyword;
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataAResponse retVal = ((Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap)(this)).GetAnalogDataA(inValue);
            return retVal.Body.GetAnalogDataAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataAResponse Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap.GetObjectDataA(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataARequest request) {
            return base.Channel.GetObjectDataA(request);
        }
        
        public Monitor_shell.Service.ServiceReference_RealTimeTagValue.ObjectDataGroup_Serialization GetObjectDataA(string myOrganizationId, Monitor_shell.Service.ServiceReference_RealTimeTagValue.ArrayOfString myTagName, string myKeyword) {
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataARequest inValue = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataARequest();
            inValue.Body = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataARequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myKeyword = myKeyword;
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetObjectDataAResponse retVal = ((Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap)(this)).GetObjectDataA(inValue);
            return retVal.Body.GetObjectDataAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSResponse Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap.GetDigitalDataS(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSRequest request) {
            return base.Channel.GetDigitalDataS(request);
        }
        
        public string GetDigitalDataS(string myOrganizationId, string myTagName, string myKeyword) {
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSRequest inValue = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSRequest();
            inValue.Body = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myKeyword = myKeyword;
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetDigitalDataSResponse retVal = ((Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap)(this)).GetDigitalDataS(inValue);
            return retVal.Body.GetDigitalDataSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSResponse Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap.GetAnalogDataS(Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSRequest request) {
            return base.Channel.GetAnalogDataS(request);
        }
        
        public string GetAnalogDataS(string myOrganizationId, string myTagName, string myKeyword) {
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSRequest inValue = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSRequest();
            inValue.Body = new Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSRequestBody();
            inValue.Body.myOrganizationId = myOrganizationId;
            inValue.Body.myTagName = myTagName;
            inValue.Body.myKeyword = myKeyword;
            Monitor_shell.Service.ServiceReference_RealTimeTagValue.GetAnalogDataSResponse retVal = ((Monitor_shell.Service.ServiceReference_RealTimeTagValue.RealTimeDataSoap)(this)).GetAnalogDataS(inValue);
            return retVal.Body.GetAnalogDataSResult;
        }
    }
}
