<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_efc_cementmill01_snfm.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_efc.zc_nxjc_qtx_efc_cementmill01snfm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_qtx_efc";
        publicData.sceneName = "4#水泥包装";
    </script>
</head>

<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_efc/zc_nxjc_qtx_efc_cementmill01_snfm.png'); width: 1480px; height: 760px; overflow: hidden;">
    <%--标签粘贴处--%>
     <%--<button onclick="CheckTags()">检查标签</button>--%>
        <%--开关量--%>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M69C1_ZD>BoolSignal" style="position: absolute; top:33px; left: 188px; height: 21px; width: 24px;" data-option="RelatedTags='Cement01_M69C1_ZRD,Cement01_M69C1_ZRN,Cement01_M69AC1_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M69C1_ZRD>BoolSignal" style="position: absolute; top:57px; left: 188px; height: 21px; width: 24px;" data-option="RelatedTags='Cement01_M69C1_ZRD,Cement01_M69C1_ZRN,Cement01_M69AC1_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L6M_RD>BoolSignal" style="position: absolute; top:435px; left: 87px; height: 18px; width: 18px;" data-option="RelatedTags='Cement01_L6M_RD,Cement01_L6M_RN,Cement01_L6M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L2M_RD>BoolSignal" style="position: absolute; top:459px; left: 146px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_L2M_RD,Cement01_L2M_RN,Cement01_L2M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M71AC_RD>BoolSignal" style="position: absolute; top:353px; left: 220px; height: 16px; width: 16px;" data-option="RelatedTags='Cement01_M71AC_RD,Cement01_M71AC_RN,Cement01_M71AC_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M61_RD>BoolSignal" style="position: absolute; top:529px; left: 217px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_M61_RD,Cement01_M61_RN,Cement01_M61_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_F_7AH_RD>BoolSignal" style="position: absolute; top:394px; left: 448px; height: 23px; width: 24px;" data-option="RelatedTags='Cement01_F_7AH_RD,Cement01_F_7AH_RN,Cement01_F_7AH_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_F_8AH_RD>BoolSignal" style="position: absolute; top:395px; left: 483px; height: 22px; width: 23px;" data-option="RelatedTags='Cement01_F_8AH_RD,Cement01_F_8AH_RN,Cement01_F_8AH_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M80_RD>BoolSignal" style="position: absolute; top:593px; left: 580px; height: 21px; width: 24px;" data-option="RelatedTags='Cement01_M80_RD,Cement01_M80_RN,Cement01_M80_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M76M_RD>BoolSignal" style="position: absolute; top:510px; left: 654px; height: 21px; width: 24px;" data-option="RelatedTags='Cement01_M76M_RD,Cement01_M76M_RN,Cement01_M76M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M74M_RD>BoolSignal" style="position: absolute; top:581px; left: 676px; height: 21px; width: 21px;" data-option="RelatedTags='Cement01_M74M_RD,Cement01_M74M_RN,Cement01_M74M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M73M_RD>BoolSignal" style="position: absolute; top:581px; left: 724px; height: 20px; width: 21px;" data-option="RelatedTags='Cement01_M73M_RD,Cement01_M73M_RN,Cement01_M73M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MFIA01_RD>BoolSignal" style="position: absolute; top:435px; left: 756px; height: 21px; width: 24px;" data-option="RelatedTags='Cement01_MFIA01_RD,Cement01_MFIA01_RN,Cement01_MFIA01_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M51BP_RD>BoolSignal" style="position: absolute; top:252px; left: 800px; height: 21px; width: 24px;" data-option="RelatedTags='Cement01_M51BP_RD,Cement01_M51BP_RN,Cement01_M51BP_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L1_3M_ALM>BoolSignal" style="position: absolute; top:224px; left: 772px; height: 21px; width: 11px;" data-option="RelatedTags='Cement01_L1_3M_ALM,Cement01_L1_3M_RD,Cement01_L1_3M_RN',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M46ALC_RD>BoolSignal" style="position: absolute; top:161px; left: 970px; height: 21px; width: 24px;" data-option="RelatedTags='Cement01_M46ALC_RD,Cement01_M46ALC_RN,Cement01_M46ALC_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_F_6AH_RD>BoolSignal" style="position: absolute; top:171px; left: 1200px; height: 23px; width: 24px;" data-option="RelatedTags='Cement01_F_6AH_RD,Cement01_F_6AH_RN,Cement01_F_6AH_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M50M_RD>BoolSignal" style="position: absolute; top:95px; left: 1364px; height: 17px; width: 19px;" data-option="RelatedTags='Cement01_M50M_RD,Cement01_M50M_RN,Cement01_M50M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M47AC_RD>BoolSignal" style="position: absolute; top:40px; left: 1406px; height: 21px; width: 14px;" data-option="RelatedTags='Cement01_M47AC_RD,Cement01_M47AC_RN,Cement01_M47AC_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>        
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M42M_RD>BoolSignal" style="position: absolute; top:265px; left: 1047px; height: 20px; width: 21px;" data-option="RelatedTags='Cement01_M42M_RD,Cement01_M42M_RN,Cement01_M42M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M37ALC_RD>BoolSignal" style="position: absolute; top:256px; left: 1101px; height: 21px; width: 24px;" data-option="RelatedTags='Cement01_M37ALC_RD,Cement01_M37ALC_RN,Cement01_M37ALC_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M38M_RD>BoolSignal" style="position: absolute; top:272px; left: 1174px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M38M_RD,Cement01_M38M_RN,Cement01_M38M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M34M_RD>BoolSignal" style="position: absolute; top:252px; left: 1227px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M34M_RD,Cement01_M34M_RN,Cement01_M34M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M30M_RD>BoolSignal" style="position: absolute; top:310px; left: 1262px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M30M_RD,Cement01_M30M_RN,Cement01_M30M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M31M_RD>BoolSignal" style="position: absolute; top:311px; left: 1309px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M31M_RD,Cement01_M31M_RN,Cement01_M31M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M32M_RD>BoolSignal" style="position: absolute; top:310px; left: 1353px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M32M_RD,Cement01_M32M_RN,Cement01_M32M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M33M_RD>BoolSignal" style="position: absolute; top:309px; left: 1402px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M33M_RD,Cement01_M33M_RN,Cement01_M33M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M40M_RD>BoolSignal" style="position: absolute; top:355px; left: 947px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M40M_RD,Cement01_M40M_RN,Cement01_M40M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M39M_RD>BoolSignal" style="position: absolute; top:355px; left: 1085px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M39M_RD,Cement01_M39M_RN,Cement01_M39M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M54AC_RD>BoolSignal" style="position: absolute; top:441px; left: 1135px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M54AC_RD,Cement01_M54AC_RN,Cement01_M54AC_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M52ALC_RD>BoolSignal" style="position: absolute; top:501px; left: 1330px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M52ALC_RD,Cement01_M52ALC_RN,Cement01_M52ALC_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M49M_RD>BoolSignal" style="position: absolute; top:721px; left: 1066px; height: 19px; width: 20px;" data-option="RelatedTags='Cement01_M49M_RD,Cement01_M49M_RN,Cement01_M49M_ERR',Display='000:grayC,001:redCB,010:greenC,011:redCB,100:yellowC,101:redC,110:greenC,111:redC'"></div>

        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L1M_RD>BoolSignal" style="position: absolute; top:424px; left: 38px; height: 11px; width: 22px;" data-option="RelatedTags='Cement01_L1M_RD,Cement01_L1M_RN,Cement01_L1M_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L7AC1_RD>BoolSignal" style="position: absolute; top:632px; left: 88px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_L7AC1_RD,Cement01_L7AC1_RN,Cement01_L7AC1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L7AC2_RD>BoolSignal" style="position: absolute; top:632px; left: 153px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_L7AC2_RD,Cement01_L7AC2_RN,Cement01_L7AC2_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L8AC2_RD>BoolSignal" style="position: absolute; top:631px; left: 222px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_L8AC2_RD,Cement01_L8AC2_RN,Cement01_L8AC2_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L8AC1_RD>BoolSignal" style="position: absolute; top:630px; left: 289px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_L8AC1_RD,Cement01_L8AC1_RN,Cement01_L8AC1_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L3AC_RD>BoolSignal" style="position: absolute; top:631px; left: 361px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_L3AC_RD,Cement01_L3AC_RN,Cement01_L3AC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M78AC_RD>BoolSignal" style="position: absolute; top:629px; left: 441px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_M78AC_RD,Cement01_M78AC_RN,Cement01_M78AC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M78AC_D>BoolSignal" style="position: absolute; top:719px; left: 528px; height: 20px; width: 14px;" data-option="RelatedTags='Cement01_M78AC_RD,Cement01_M78AC_RN,Cement01_M78AC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M57ALC_RD>BoolSignal" style="position: absolute; top:706px; left: 746px; height: 13px; width: 14px;" data-option="RelatedTags='Cement01_M57ALC_RD,Cement01_M57ALCL_RN1,Cement01_M57ALC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M57ALCL_RN2>BoolSignal" style="position: absolute; top:706px; left: 766px; height: 13px; width: 13px;" data-option="RelatedTags='Cement01_M57ALC_RD,Cement01_M57ALCL_RN2,Cement01_M57ALC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M56ALC_RD>BoolSignal" style="position: absolute; top:707px; left: 907px; height: 14px; width: 14px;" data-option="RelatedTags='Cement01_M56ALC_RD,Cement01_M56ALCL_RN2,Cement01_M56ALC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M56ALCL_RN1>BoolSignal" style="position: absolute; top:707px; left: 925px; height: 14px; width: 14px;" data-option="RelatedTags='Cement01_M56ALC_RD,Cement01_M56ALCL_RN1,Cement01_M56ALC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M67MJSJ_RD>BoolSignal" style="position: absolute; top:208px; left: 796px; height: 15px; width: 26px;" data-option="RelatedTags='Cement01_M67MJSJ_RD,Cement01_M67MJSJ_RN,Cement01_M67MJSJ_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M64AC_RD>BoolSignal" style="position: absolute; top:410px; left: 361px; height: 16px; width: 46px;" data-option="RelatedTags='Cement01_M64AC_RD,Cement01_M64AC_RN,Cement01_M64AC_FL',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_DSZ_RD>BoolSignal" style="position: absolute; top:386px; left: 529px; height: 14px; width: 23px;" data-option="RelatedTags='Cement01_DSZ_RD,Cement01_DSZ_RN,Cement01_DSZ_FL',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_CSZ_RD>BoolSignal" style="position: absolute; top:412px; left: 530px; height: 14px; width: 23px;" data-option="RelatedTags='Cement01_CSZ_RD,Cement01_CSZ_RN,Cement01_CSZ_FL',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M66YV_RD>BoolSignal" style="position: absolute; top:143px; left: 440px; height: 10px; width: 37px;" data-option="RelatedTags='Cement01_M66YV_RD,Cement01_M66YV_RN,Cement01_M67M_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_PFS_RD>BoolSignal" style="position: absolute; top:203px; left: 1247px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_PFS_RD,Cement01_PFS_RN,Cement01_PFS_BJ',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_PM2_RD>BoolSignal" style="position: absolute; top:217px; left: 1247px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_PM2_RD,Cement01_PM2_ST,Cement01_PM2_BJ',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_F_5AH_RD>BoolSignal" style="position: absolute; top:595px; left: 1136px; height: 36px; width: 17px;" data-option="RelatedTags='Cement01_F_5AH_RD,Cement01_F_5AH_RN,Cement01_F_5AH_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M58ALC_RD>BoolSignal" style="position: absolute; top:577px; left: 1258px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_M58ALC_RD,Cement01_M58ALCL_RN1,Cement01_M58ALC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M58ALCL_RN2>BoolSignal" style="position: absolute; top:597px; left: 1258px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_M58ALC_RD,Cement01_M58ALCL_RN2,Cement01_M58ALC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M59ALCL_RN1>BoolSignal" style="position: absolute; top:618px; left: 1258px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_M59ALC_RD,Cement01_M59ALCL_RN1,Cement01_M59ALC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M59ALCL_RN2>BoolSignal" style="position: absolute; top:637px; left: 1258px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_M59ALC_RD,Cement01_M59ALCL_RN2,Cement01_M59ALC_ERR',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MMJ1_ST>BoolSignal" style="position: absolute; top:657px; left: 1250px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_MMS_RD,Cement01_MMJ1_ST,Cement01_MMJ1_BJ',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>
        <div class="BoolSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MMS_RD>BoolSignal" style="position: absolute; top:676px; left: 1250px; height: 17px; width: 17px;" data-option="RelatedTags='Cement01_MMS_RD,Cement01_MMS_RN,Cement01_MMS_BJ',Display='000:grayS,001:redSB,010:greenS,011:redSB,100:yellowS,101:redS,110:greenS,111:redS'"></div>

        <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M70M1_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 32px; left: 124px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M70M2_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 58px; left: 124px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M_II_01R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 162px; left: 123px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M17M_1R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 183px; left: 123px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Cement01_M76M_I_R>DCS'" style="width:47px; display:block; top: 203px; left: 121px; position:absolute;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_AI_1PWIA01R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 224px; left: 123px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_AI_1PWIA02R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 244px; left: 123px; position:absolute;color:#4cff00;text-align:right; bottom: 500px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MPT04_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 161px; left: 377px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MPT05_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 162px; left: 529px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_W305_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:40px; display:block; top: 255px; left: 468px; position:absolute;color:blue;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_F_7AH_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 324px; left: 361px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M64AC_LF_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 345px; left: 360px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M64AC_LP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 365px; left: 359px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_GZK004_ZKR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 385px; left: 360px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M71AC_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 379px; left: 248px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M71AC_S_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 402px; left: 248px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_F_8AH_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 323px; left: 580px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M64AC_RF_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 344px; left: 578px; position:absolute;color:#4cff00;text-align:right; right: 856px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M64AC_RP_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 365px; left: 578px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_GZK004_ZFR>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 385px; left: 580px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE42_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 432px; left: 296px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE46_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 452px; left: 296px; position:absolute;color:#4cff00;text-align:right;"></div>                                                                                                                                                            
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE50_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 472px; left: 296px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE54_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 492px; left: 296px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE43_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 432px; left: 354px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE47_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 452px; left: 354px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE51_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 472px; left: 354px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE55_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 493px; left: 354px; position:absolute;color:#4cff00;text-align:right; right: 1080px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE44_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 432px; left: 414px; position:absolute;color:#4cff00;text-align:right; bottom: 312px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE48_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 452px; left: 414px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE52_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 472px; left: 414px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE56_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 493px; left: 414px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE45_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 432px; left: 472px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE49_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 452px; left: 472px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE53_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 472px; left: 472px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE57_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 493px; left: 472px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_TE04_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 432px; left: 530px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_TE02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 453px; left: 530px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_TE05_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 473px; left: 530px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_TE08_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 493px; left: 530px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_TE06_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 432px; left: 589px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_TE03_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 453px; left: 589px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_TE07_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 472px; left: 589px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_TE09_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 493px; left: 589px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M61_S_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 546px; left: 354px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M61_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 545px; left: 250px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_SUM_SET_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 589px; left: 119px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_ZLLJ_R3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 589px; position:absolute;color:#4cff00;text-align:right; right: 1147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_ZLLJ_R5>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:46px; display:block; top: 590px; left: 446px; position:absolute;color:#4cff00;text-align:right;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L7AC1_P>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 650px; left: 89px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L7AC1_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 672px; left: 89px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L7AC1_F_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 696px; left: 89px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L7AC1_F_LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 718px; left: 89px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L7AC2_P>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 650px; left: 155px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L7AC2_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 672px; left: 155px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L7AC2_F_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 695px; left: 155px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L7AC2_F_LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 717px; left: 155px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L8AC2_P>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 649px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L8AC2_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 671px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L8AC2_F_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 693px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L8AC2_F_LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 716px; left: 227px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L8AC1_P>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 648px; left: 293px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L8AC1_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 669px; left: 293px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L8AC1_F_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 692px; left: 293px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L8AC1_F_LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 716px; left: 293px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L3AC_P>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 648px; left: 367px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L3AC_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 669px; left: 367px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L3AC_F_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 692px; left: 367px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_L3AC_F_LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 715px; left: 367px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M78AC_P>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 647px; left: 447px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M78AC_SP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 670px; left: 447px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M78AC_F_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 692px; left: 447px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M78AC_F_LJ>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 714px; left: 447px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MLT12_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 637px; left: 557px; position:absolute;color:blue;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MZZ04_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 265px; left: 715px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M51AC_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 44px; display: block; top: 225px; left: 790px; position: absolute; color: blue; text-align: right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MPT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 152px; left: 842px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTT02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 188px; left: 865px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M51AC_S_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 221px; left: 858px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MZZ02_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 110px; left: 1038px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MPT03_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 156px; left: 1044px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTT03_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 185px; left: 1060px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MZZ01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 151px; left: 1121px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_F_6AH_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 202px; left: 1188px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M48M_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 35px; left: 1333px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M34M_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 40px; display: block; top: 249px; left: 1275px; position: absolute; color: #4cff00; text-align: right"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE31_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 122px; left: 1244px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE33_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 141px; left: 1244px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE34_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 162px; left: 1244px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE36_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 181px; left: 1244px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE37_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 140px; left: 1295px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE38_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 162px; left: 1295px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE30_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 181px; left: 1295px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE35_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 141px; left: 1348px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE32_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 161px; left: 1347px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE29_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 181px; left: 1347px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE39_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 258px; left: 860px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTT67_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 277px; left: 860px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE41_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 296px; left: 860px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE40_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 317px; left: 860px; position:absolute;color:#4cff00;text-align:right; height: 18px; bottom: 425px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MZZ03_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 430px; left: 1284px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M54AC_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 468px; left: 1115px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 518px; left: 1117px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MPT01_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 540px; left: 1117px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTT04_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 516px; left: 1225px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MPT06_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 539px; left: 1226px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MFIA01_F_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 402px; left: 810px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_M76M_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 481px; left: 663px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE17_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 464px; left: 805px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE22_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 489px; left: 806px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE27_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 512px; left: 806px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE11_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 535px; left: 806px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE14_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 559px; left: 806px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE21_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 464px; left: 875px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE26_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 488px; left: 875px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE20_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 512px; left: 875px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE13_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 535px; left: 874px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE16_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 560px; left: 874px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE25_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 463px; left: 941px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE19_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 488px; left: 941px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE24_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 511px; left: 941px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE15_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 535px; left: 941px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE09_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 560px; left: 941px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE18_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 463px; left: 1010px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE23_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 487px; left: 1010px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE28_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 512px; left: 1010px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE12_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 535px; left: 1010px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE10_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 559px; left: 1010px; position:absolute;color:#4cff00;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE07_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 591px; left: 832px; position:absolute;color:blue;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE05_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 590px; left: 967px; position:absolute;color:blue;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_F_5AH_I_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 618px; left: 915px; position:absolute;color:blue;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE08_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 646px; left: 834px; position:absolute;color:blue;text-align:right; height: 18px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_efc>Cement01_MTE06_R>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:47px; display:block; top: 643px; left: 969px; position:absolute;color:blue;text-align:right; height: 18px;"></div>

         <%--汉字隐藏--%>
        <div id="zc_nxjc_qtx_efc>Cement01_M69C1_FL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 43px; left: 211px; color: red; text-align: center; height: 28px; right: 1255px; bottom: 689px;">故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M69C2_FL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 83px; left: 193px; color: red; text-align: center; height: 28px; right: 1273px; bottom: 649px;">故障</div> 
        <div id="zc_nxjc_qtx_efc>Cement01_CSZ_TZ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 206px; left: 334px; color: red; text-align: center; height: 14px; bottom: 540px;">水电阻主机跳闸</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_8AH_MC>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 225px; left: 332px; color: red; text-align: center; height: 14px; right: 1044px; bottom: 521px;">主电机保护动作</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_8AH_FLT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 244px; left: 332px; color: red; text-align: center; height: 14px; right: 1044px; bottom: 502px;">主电机事故跳闸</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_8AH_MC_FLT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 264px; left: 334px; color: red; text-align: center; height: 14px; right: 1020px; bottom: 482px;">主电机保护装置故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_DSZ_TZ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 206px; left: 537px; color: red; text-align: center; height: 14px; right: 839px; bottom: 540px;">水电阻主机跳闸</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_7AH_MC>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 225px; left: 537px; color: red; text-align: center; height: 14px; right: 839px; bottom: 521px;">主电机保护动作</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_7AH_FLT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 244px; left: 536px; color: red; text-align: center; height: 14px; right: 840px; bottom: 502px;">主电机事故跳闸</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_7AH_MC_FLT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 263px; left: 538px; color: red; text-align: center; height: 14px; right: 816px; bottom: 483px;">主电机保护装置故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_CSZ_SO>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 284px; left: 536px; color: #4cff00; text-align: center; height: 14px; right: 840px; bottom: 462px;">水电阻启动完毕</div>
        <div id="zc_nxjc_qtx_efc>Cement01_DSZ_SO>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 285px; left: 332px; color: #4cff00; text-align: center; height: 14px; right: 1044px; bottom: 461px;">水电阻启动完毕</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M64AC_CL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 312px; left: 444px; color: #4cff00; text-align: center; height: 14px; right: 1006px; bottom: 434px;">关</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M64AC_OP>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 312px; left: 514px; color: #4cff00; text-align: center; height: 14px; right: 943px; bottom: 434px; width: 23px;">开</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M64AC_AL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 306px; left: 555px; color: #4cff00; text-align: center; height: 14px; right: 821px; bottom: 440px;">允许主机运行</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M64AC_FL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 322px; left: 293px; color: red; text-align: center; height: 14px; right: 1133px; bottom: 424px;">综合故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M64AC_BJ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 340px; left: 291px; color: red; text-align: center; height: 14px; right: 1118px; bottom: 406px;">控制柜报警</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M64AC_YFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 357px; left: 293px; color: red; text-align: center; height: 14px; right: 1123px; bottom: 389px;">液压系统故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M64AC_HFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 376px; left: 292px; color: red; text-align: center; height: 14px; right: 1127px; bottom: 370px;">润滑系统故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M64AC_GFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 394px; left: 291px; color: red; text-align: center; height: 14px; right: 1120px; bottom: 352px;">干油站故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M64AC_ZFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 10px; top: 411px; left: 293px; color: red; text-align: center; height: 15px; right: 1124px; bottom: 334px;">轴承超限报警</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M69M_JT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 486px; left: 191px; color: red; text-align: center; height: 90px; right: 1271px; bottom: 184px;">下部急停动作</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M61_FL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 530px; left: 254px; color: red; text-align: center; height: 14px; right: 1196px; bottom: 216px;">故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M47AC_FL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 74px; left: 1406px; color: red; text-align: center; height: 29px; right: 61px; bottom: 657px;">故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_6AH_MC>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 90px; color: red; text-align: center; height: 14px; right: 264px; bottom: 656px;">主电机保护动作</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_6AH_FLT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 109px; left: 1117px; color: red; text-align: center; height: 14px; right: 259px; bottom: 637px;">主电机事故跳闸</div>
        <div id="zc_nxjc_qtx_efc>Cement01_PFS_TZ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 128px; left: 1117px; color: red; text-align: center; height: 14px; right: 259px; bottom: 618px;">水电阻主机跳闸</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_6AH_MC_FLT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 208px; left: 1029px; color: red; text-align: center; height: 14px; right: 319px; bottom: 538px;">主电机保护装置故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_PM2_BJ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 227px; left: 1029px; color: red; text-align: center; height: 14px; right: 317px; bottom: 519px;">进相器转子开路报警</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M67MJSJ_RF>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 245px; left: 992px; color: red; text-align: center; height: 14px; right: 384px; bottom: 501px;">减速机油压高</div>
        <div id="zc_nxjc_qtx_efc>Cement01_MZZ01_LIM>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 186px; left: 1100px; color: #4cff00; text-align: center; height: 14px; right: 276px; bottom: 560px;">关限位</div>
        <div id="zc_nxjc_qtx_efc>Cement01_PFS_SO>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 201px; left: 1269px; color: #4cff00; text-align: center; height: 14px; right: 107px; bottom: 545px;">水电阻启动完毕</div>
        <div id="zc_nxjc_qtx_efc>Cement01_PM2_AL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 216px; left: 1269px; color: #4cff00; text-align: center; height: 14px; right: 107px; bottom: 530px;">进相器允许进相</div>
        <div id="zc_nxjc_qtx_efc>Cement01_MZZ03_LIM>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 467px; left: 1226px; color: #4cff00; text-align: center; height: 14px; right: 179px; bottom: 279px;">关限位</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M51BP_FL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 276px; left: 786px; color: red; text-align: center; height: 14px; right: 642px; bottom: 470px;">故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M46ALC_RD>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 195px; left: 957px; color: red; text-align: center; height: 14px; right: 471px; bottom: 551px;">故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_MFIA01_FLT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 439px; left: 781px; color: red; text-align: center; height: 14px; right: 663px; bottom: 307px;">故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M54AC_FL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 445px; left: 1088px; color: red; text-align: center; height: 14px; right: 351px; bottom: 301px;">故障</div>
        <%--<div id="zc_nxjc_qtx_efc>Cement01_M54AC_FL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 526px; left: 1321px; color: red; text-align: center; height: 14px; right: 118px; bottom: 220px;">故障</div>--%>
        <div class="Conflict"  data-option="id='zc_nxjc_qtx_efc>Cement01_M54AC_FL>DCS'" style="position: absolute; font-size: 14px; top: 526px; left: 1321px; color: red; text-align: center; height: 14px; right: 118px; bottom: 220px;" >故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_MFIA01_H>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 428px; left: 712px; color: red; text-align: center; height: 14px; right: 727px; bottom: 318px;">高报</div>
        <div id="zc_nxjc_qtx_efc>Cement01_MFIA01_L>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 446px; left: 712px; color: red; text-align: center; height: 14px; right: 727px; bottom: 300px;">低报</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M34M_JT1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 333px; left: 1228px; color: red; text-align: center; height: 92px; right: 233px; bottom: 335px;">下部急停动作</div>
        <div id="zc_nxjc_qtx_efc>Cement01_MMJ1_BJ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 638px; left: 1111px; color: red; text-align: center; height: 14px; right: 237px; bottom: 108px;">进相器转子开路报警</div>
        <div id="zc_nxjc_qtx_efc>Cement01_MMS_TZ>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 658px; left: 1112px; color: red; text-align: center; height: 15px; right: 265px; bottom: 87px;">水电阻主机跳闸</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_5AH_DP_FLT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 680px; left: 1110px; color: red; text-align: center; height: 14px; right: 228px; bottom: 66px;">主电机差动保护装置故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_5AH_DP>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 701px; left: 1113px; color: red; text-align: center; height: 14px; right: 265px; bottom: 45px;">主电机差动保护</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_5AH_MC>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 722px; left: 1115px; color: red; text-align: center; height: 14px; bottom: 24px;">主电机保护动作</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_5AH_FLT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 701px; left: 1262px; color: red; text-align: center; height: 14px; right: 115px; bottom: 45px;">主电机事故跳闸</div>
        <div id="zc_nxjc_qtx_efc>Cement01_F_5AH_MC_FLT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 721px; left: 1259px; color: red; text-align: center; height: 14px; right: 85px; bottom: 25px;">主电机保护装置故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M58ALC_LFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 598px; left: 1281px; color: red; text-align: center; height: 14px; right: 142px; bottom: 148px;">轻故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M58ALC_HFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 598px; left: 1344px; color: red; text-align: center; height: 14px; right: 92px; bottom: 148px;">重故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M59ALC_LFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 638px; left: 1281px; color: red; text-align: center; height: 14px; right: 142px; bottom: 108px;">轻故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M59ALC_HFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 638px; left: 1345px; color: red; text-align: center; height: 14px; right: 91px; bottom: 108px;">重故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M47M_JT>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 636px; left: 1404px; color: red; text-align: center; height: 88px; right: 57px; bottom: 36px;">下部急停动作</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M58ALC_AL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 578px; left: 1277px; color: #4cff00; text-align: center; height: 14px; right: 105px; bottom: 168px;">允许主机运行</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M59ALC_AL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 617px; left: 1276px; color: #4cff00; text-align: center; height: 14px; right: 106px; bottom: 129px;">允许主机运行</div>
        <div id="zc_nxjc_qtx_efc>Cement01_MMJ1_AL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 656px; left: 1277px; color: #4cff00; text-align: center; height: 14px; right: 105px; bottom: 90px;">进相器允许进相</div>
        <div id="zc_nxjc_qtx_efc>Cement01_MMS_SO>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 14px; top: 678px; left: 1277px; color: #4cff00; text-align: center; height: 14px; right: 105px; bottom: 68px;">水电阻启动完毕</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M57ALC_AL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 706px; left: 792px; color: #4cff00; text-align: center; height: 14px; right: 590px; bottom: 40px;">允许主机运行</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M56ALC_AL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 706px; left: 949px; color: #4cff00; text-align: center; height: 14px; right: 433px; bottom: 40px;">允许主机运行</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M57ALCH_RN1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 723px; left: 791px; color: #4cff00; text-align: center; height: 14px; right: 591px; bottom: 23px;">1#高压泵运行</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M57ALCH_RN2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 740px; left: 790px; color: #4cff00; text-align: center; height: 14px; right: 592px; bottom: 6px;">2#高压泵运行</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M56ALCH_RN1>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 723px; left: 956px; color: #4cff00; text-align: center; height: 14px; bottom: 23px;">1#高压泵运行</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M56ALCH_RN2>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 741px; left: 949px; color: #4cff00; text-align: center; height: 14px; right: 433px; bottom: 5px;">2#高压泵运行</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M57ALC_LFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 722px; left: 737px; color: red; text-align: center; height: 14px; right: 686px; bottom: 24px;">轻故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M57ALC_HFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 738px; left: 743px; color: red; text-align: center; height: 14px; right: 693px; bottom: 8px;">重故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M56ALC_LFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 723px; left: 897px; color: red; text-align: center; height: 14px; right: 526px; bottom: 23px;">轻故障</div>
        <div id="zc_nxjc_qtx_efc>Cement01_M56ALC_HFL>DCS" class="TextDisplay" data-option="Display='1'" style="position: absolute; font-size: 12px; top: 739px; left: 902px; color: red; text-align: center; height: 14px; right: 534px; bottom: 7px;">重故障</div>








    </div>
</body>
</html>
