<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="zc_nxjc_qtx_tys_clinker04_scbb.aspx.cs" Inherits="Monitor_qtx.Web.UI_Monitor.DCSMonitor.zc_nxjc_qtx_tys.zc_nxjc_qtx_tys_clinker04_scbb" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/gray/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/lib/ealib/themes/icon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtIcon.css" />
    <link rel="stylesheet" type="text/css" href="/lib/extlib/themes/syExtCss.css" />

    <link rel="stylesheet" type="text/css" href="/UI_Monitor/css/common/mymonitor.css" />

    <script type="text/javascript" src="/lib/ealib/jquery.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/common/jquery.utility.js" charset="utf-8"></script>
    <!--[if lt IE 8 ]><script type="text/javascript" src="/js/common/json2.min.js"></script><![endif]-->

    <script type="text/javascript" src="/lib/ealib/jquery.easyui.min.js" charset="utf-8"></script>
    <script type="text/javascript" src="/lib/ealib/easyui-lang-zh_CN.js" charset="utf-8"></script>

    <script src="/UI_Monitor/js/common/DCSTagInfo.js"></script>
    <script src="/UI_Monitor/js/common/monitorjs.js"></script>
    <script src="/UI_Monitor/js/common/chartjs.js"></script>
    <script src="/UI_Monitor/js/common/SubMonitorAdapter.js"></script>
    <script src="/UI_Monitor/js/common/alarm.js"></script>
    <script src="/UI_Monitor/js/common/multiTagChart.js"></script>
    <script src="/UI_Monitor/js/common/RunningState.js"></script>
    <script src="/UI_Monitor/js/common/AmmeterStatistic.js"></script>
    <script src="/UI_Monitor/js/common/EquipmentInfo.js"></script>
    <script src="/UI_Monitor/js/common/DisplayName.js"></script>
    <script src="/UI_Monitor/js/common/myDrag.js"></script>
    <script src="../../DCSMonitor/js/common/OptionHelper.js"></script>
    <script src="../../js/common/DCSMonitorShell.js"></script>
    
    <script>
        publicData.organizationId = "zc_nxjc_qtx_tys_clinker04";
        publicData.sceneName = "4#生产报表";
   </script>
</head>
<body id="SubMonitorBody" style="margin: 0px; padding: 0px; overflow: auto;">
    <div id="SubMonitorLayout" style="position: relative; background-image: url('../../images/page/DCS/zc_nxjc_qtx_tys/zc_nxjc_qtx_tys_clinker04_scbb.png'); width: 1558px; height: 809px; overflow: hidden;">
        <%--标签粘贴处--%>
        <%--<button onclick="CheckTags()">检查标签</button>--%>
        <%--开关量--%>
        <%-- <div class="BoolSignal mchart" id="zc_nxjc_qtx_tys>Clinker03_DI1_330_20>BoolSignal" style="position: absolute; top: 87px; left: 14px; height: 36px; width: 25px;" data-option="RelatedTags='Clinker03_DI1_330_20,Clinker03_DI2_330_20,,,,Clinker03_F_330_20ALM,'"></div>        
       <div class="BoolSignal mchart" id="zc_nxjc_qtx_tys>Clinker03_DI1_330_21>BoolSignal" style="position: absolute; top: 141px; left: 16px; height: 25px; width: 25px;" data-option="RelatedTags='Clinker03_DI1_330_21,Clinker03_DI2_330_21,,,,Clinker03_F_330_21ALM,'"></div>--%>
        <%--模拟量--%>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SLZLJ_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 64px; left: 253px; position: absolute; color: #4cff00; text-align: right; height: 20px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SLZLJ_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 64px; left: 392px; position: absolute; color: #4cff00; text-align: right; height: 19px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SLZLJ_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 64px; left: 533px; position: absolute; color: #4cff00; text-align: right; height: 19px; right: 890px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SLZLJ_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 64px; left: 674px; position: absolute; color: #4cff00; text-align: right; height: 23px; right: 754px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SLZLJ_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 62px; left: 814px; position: absolute; color: #4cff00; text-align: right; height: 22px; right: 609px; bottom: 725px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SLZLJ_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 65px; position: absolute; color: #4cff00; text-align: right; height: 19px; right: 471px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SLZLJ_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 65px; position: absolute; color: #4cff00; text-align: right; height: 19px; right: 331px; bottom: 725px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SLZLJ_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 64px; position: absolute; color: #4cff00; text-align: right; height: 21px; right: 190px; left: 1236px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SLZLJ_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 63px; position: absolute; color: #4cff00; text-align: right; height: 22px; right: 51px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 90px; position: absolute; color: #4cff00; text-align: right; height: 23px; right: 1172px; left: 252px; bottom: 696px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 90px; position: absolute; color: #4cff00; text-align: right; height: 23px; right: 1033px; left: 392px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 88px; position: absolute; color: #4cff00; text-align: right; height: 24px; left: 534px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 90px; position: absolute; color: #4cff00; text-align: right; height: 23px; right: 754px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 88px; position: absolute; color: #4cff00; text-align: right; height: 23px; right: 611px; left: 814px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 88px; position: absolute; color: #4cff00; text-align: right; height: 23px; right: 469px; left: 955px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 88px; position: absolute; color: #4cff00; text-align: right; height: 23px; right: 328px; left: 1094px; bottom: 698px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 88px; position: absolute; color: #4cff00; text-align: right; height: 23px; right: 51px; left: 1375px; bottom: 698px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 89px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1236px; bottom: 698px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LB1TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 116px; position: absolute; color: #4cff00; text-align: right; height: 18px; left: 251px; bottom: 675px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LB2TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 114px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 393px; bottom: 672px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LB3TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 116px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 534px; bottom: 670px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LDPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 117px; position: absolute; color: #4cff00; text-align: right; height: 19px; left: 672px; bottom: 673px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LDCTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 112px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 814px; right: 612px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LMPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 115px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 955px; bottom: 671px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LMCTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 116px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1094px; bottom: 671px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W32001AR1_LYPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 113px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 1236px; bottom: 673px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_qtx_tys>dcs01_W32001AR1_LYPTS>DCS'" style="width:133px; display:block; top: 112px; position:absolute;color:#4cff00;text-align:right; height: 23px; left: 1374px; bottom: 674px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YLMLB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 143px; position: absolute; color: #4cff00; text-align: right; height: 19px; left: 250px; bottom: 647px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YLMLB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 142px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 646px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YLMLB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 140px; position: absolute; color: #4cff00; text-align: right; left: 533px; bottom: 645px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YLMLLDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 141px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 672px; bottom: 645px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YLMLLDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 141px; position: absolute; color: #4cff00; text-align: right; left: 809px; bottom: 646px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YLMLLMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 142px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 954px; bottom: 647px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YLMLLMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 142px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YLMLLYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 142px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 1234px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YLMLLYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 142px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 166px; position: absolute; color: #4cff00; text-align: right; height: 24px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LB1TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 194px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 595px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43002AR_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 221px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 247px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 252px; bottom: 542px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LB1TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 273px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 251px; bottom: 513px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 298px; position: absolute; color: #4cff00; text-align: right; height: 24px; left: 252px; bottom: 488px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_TLB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 326px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 252px; bottom: 463px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LB1TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 352px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 253px; bottom: 437px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SNMLB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 381px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 251px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 406px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 383px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LB1TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 432px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 251px; bottom: 357px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W22107F01_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 457px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 250px; bottom: 330px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43111_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 483px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 249px; bottom: 304px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43112_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 508px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21010W01_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 535px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 250px; bottom: 250px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21011W01_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 562px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21012W01_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 589px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21013W01_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 616px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YFMH_F_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 643px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55012F01_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 670px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55013F01_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 697px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55014F01_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 724px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55015F01_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 751px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N53302F01_LB1>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 778px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 250px; bottom: 619px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 171px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 617px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LB2TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 198px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43002AR_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 222px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 250px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 392px; bottom: 536px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LB2TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 276px; position: absolute; color: #4cff00; text-align: right; height: 19px; left: 392px; bottom: 514px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 301px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 487px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_TLB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 327px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 461px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LB2TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 353px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 392px; bottom: 434px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SNMLB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 380px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 434px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 406px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 434px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LB2TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 432px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 434px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W22107F01_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 458px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 434px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43111_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 482px; position: absolute; color: #4cff00; text-align: right; height: 24px; left: 392px; bottom: 303px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43112_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 509px; position: absolute; color: #4cff00; text-align: right; height: 19px; left: 392px; bottom: 281px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21010W01_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 539px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 434px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21011W01_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 564px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 392px; bottom: 222px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21012W01_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 589px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 392px; bottom: 195px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21013W01_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 617px; position: absolute; color: #4cff00; text-align: right; height: 24px; left: 392px; bottom: 168px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YFMH_F_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 643px; position: absolute; color: #4cff00; text-align: right; height: 19px; left: 392px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55012F01_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 670px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 392px; bottom: 117px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55013F01_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 698px; position: absolute; color: #4cff00; text-align: right; height: 24px; left: 392px; bottom: 87px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55014F01_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 725px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 392px; bottom: 63px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55015F01_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 748px; position: absolute; color: #4cff00; text-align: right; height: 23px; bottom: 38px; right: 1035px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N53302F01_LB2>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 775px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 392px; bottom: 11px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 168px; position: absolute; color: #4cff00; text-align: right; left: 534px; bottom: 616px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LB3TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 192px; position: absolute; color: #4cff00; text-align: right; left: 533px; bottom: 593px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43002AR_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 221px; position: absolute; color: #4cff00; text-align: right; left: 533px; height: 22px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 248px; position: absolute; color: #4cff00; text-align: right; left: 533px; bottom: 539px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LB3TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 275px; position: absolute; color: #4cff00; text-align: right; left: 529px; bottom: 511px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 301px; position: absolute; color: #4cff00; text-align: right; left: 529px; height: 23px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_TLB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 326px; position: absolute; color: #4cff00; text-align: right; left: 529px; bottom: 461px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LB3TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 352px; position: absolute; color: #4cff00; text-align: right; left: 529px; bottom: 437px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SNMLB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 379px; position: absolute; color: #4cff00; text-align: right; left: 529px; bottom: 411px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 403px; position: absolute; color: #4cff00; text-align: right; left: 529px; bottom: 382px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LB3TS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 430px; position: absolute; color: #4cff00; text-align: right; left: 529px; bottom: 353px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W22107F01_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 459px; position: absolute; color: #4cff00; text-align: right; left: 533px; bottom: 329px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43111_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 483px; position: absolute; color: #4cff00; text-align: right; left: 531px; bottom: 304px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43112_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 510px; position: absolute; color: #4cff00; text-align: right; left: 531px; bottom: 280px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21010W01_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 537px; position: absolute; color: #4cff00; text-align: right; left: 531px; bottom: 249px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21011W01_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 564px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 531px; bottom: 249px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21012W01_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 590px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 531px; bottom: 249px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21013W01_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 617px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 531px; bottom: 169px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YFMH_F_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 642px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 531px; bottom: 144px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55012F01_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 670px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 529px; bottom: 249px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55013F01_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 697px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 529px; bottom: 92px; right: 891px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55014F01_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 722px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 529px; bottom: 249px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55015F01_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 748px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 529px; bottom: 249px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N53302F01_LB3>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 774px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 529px; bottom: 249px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 167px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 672px; bottom: 645px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LDPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 193px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 672px; bottom: 645px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43002AR_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 219px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 672px; bottom: 569px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 248px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 673px; bottom: 540px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LDPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 273px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 673px; bottom: 515px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 300px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 673px; bottom: 488px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_TLDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 326px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 673px; bottom: 462px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LDPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 353px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 672px; bottom: 436px; right: 753px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SNMLLDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 379px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 672px; bottom: 409px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 404px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 672px; bottom: 384px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LDPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 431px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 672px; bottom: 357px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W22107F01_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 456px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 673px; bottom: 332px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43111_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 483px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 672px; bottom: 305px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43112_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 508px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 671px; bottom: 280px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21010W01_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 671px; bottom: 250px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21011W01_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 560px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 671px; bottom: 226px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21012W01_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 586px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 671px; bottom: 198px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21013W01_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 618px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 674px; bottom: 166px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YFMH_F_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 644px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 673px; bottom: 144px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55012F01_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 667px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 671px; bottom: 281px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55013F01_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 693px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 671px; bottom: 281px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55014F01_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 719px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 671px; bottom: 281px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55015F01_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 746px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 671px; bottom: 281px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N53302F01_LDP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 772px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 671px; bottom: 281px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 167px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 809px; bottom: 646px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LDCTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 193px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 809px; bottom: 646px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43002AR_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 222px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 565px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 248px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 812px; bottom: 539px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LDCTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 273px; position: absolute; color: #4cff00; text-align: right; height: 20px; left: 809px; bottom: 516px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 299px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 488px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_TLDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 326px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 809px; bottom: 462px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LDCTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 352px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SNMLLDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 379px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 406px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LDCTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 432px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W22107F01_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 459px; position: absolute; color: #4cff00; text-align: right; height: 24px; left: 811px; bottom: 326px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43111_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 486px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43112_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 512px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21010W01_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 538px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21011W01_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 565px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21012W01_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 591px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21013W01_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 617px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YFMH_F_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 644px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55012F01_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 670px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55013F01_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 696px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55014F01_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 722px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55015F01_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 748px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N53302F01_LDC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 774px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 809px; bottom: 435px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 167px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LMPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 194px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43002AR_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 220px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 246px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LMPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 273px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 299px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_TLMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 326px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LMPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 353px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SNMLLMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 379px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 405px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LMPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 431px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W22107F01_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 457px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43111_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 483px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43112_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 509px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 955px; bottom: 648px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21010W01_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 535px; position: absolute; color: #4cff00; text-align: right; height: 24px; left: 955px; bottom: 250px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21011W01_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 563px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 955px; bottom: 221px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21012W01_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 591px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 955px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21013W01_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 615px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 955px; bottom: 172px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YFMH_F_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 640px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 955px; bottom: 146px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55012F01_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 666px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 955px; bottom: 146px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55013F01_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 692px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 955px; bottom: 146px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55014F01_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 718px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 955px; bottom: 146px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55015F01_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 744px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 955px; bottom: 146px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N53302F01_LMP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 770px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 955px; bottom: 146px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 168px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LMCTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 194px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43002AR_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 220px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 246px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LMCTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 272px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 298px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_TLMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 324px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LMCTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 350px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SNMLLMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 376px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 402px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LMCTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 428px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W22107F01_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 454px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43111_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 480px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43112_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 506px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 1094px; bottom: 278px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21010W01_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 535px; position: absolute; color: #4cff00; text-align: right; height: 24px; left: 1094px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21011W01_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 562px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1094px; bottom: 225px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21012W01_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 589px; position: absolute; color: #4cff00; text-align: right; height: 24px; left: 1094px; bottom: 196px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21013W01_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 615px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1094px; bottom: 173px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YFMH_F_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 640px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1094px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55012F01_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 667px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1094px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55013F01_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 693px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1094px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55014F01_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 720px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1094px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55015F01_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 746px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1094px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N53302F01_LMC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 772px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1094px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 168px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LYPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:133px; display:block; top: 193px; position:absolute;color:#4cff00;text-align:right; height: 21px; left: 1234px; bottom: 595px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43002AR_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 220px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 246px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LYPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 272px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 298px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_TLYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 324px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LYPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 350px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SNMLLYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 376px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 402px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LYPTS>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 428px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 644px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W22107F01_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 457px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 331px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43111_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 482px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1235px; bottom: 305px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43112_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 510px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 278px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21010W01_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 538px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 250px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21011W01_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 563px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 225px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21012W01_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 590px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1236px; bottom: 198px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21013W01_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 617px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1235px; bottom: 171px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YFMH_F_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 641px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1236px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55012F01_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 670px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1234px; bottom: 118px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55013F01_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 695px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1236px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55014F01_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 721px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1236px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55015F01_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 747px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1236px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N53302F01_LYP>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 774px; position: absolute; color: #4cff00; text-align: right; height: 21px; left: 1236px; bottom: 147px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y211021_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 168px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1374px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_qtx_tys>dcs01_Y211021_LYPTS>DCS'" style="width:133px; display:block; top: 192px; position:absolute;color:#4cff00;text-align:right; height: 22px; left: 1373px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43002AR_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 220px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43004M_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 246px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1374px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_qtx_tys>dcs01_T43004M_LYPTS>DCS'" style="width:133px; display:block; top: 272px; position:absolute;color:#4cff00;text-align:right; height: 22px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 298px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_JZ3_TLYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 324px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1374px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_qtx_tys>dcs01_JZ3_LYPTS>DCS'" style="width:133px; display:block; top: 350px; position:absolute;color:#4cff00;text-align:right; height: 22px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_SNMLLYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 376px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55116_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 402px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1374px;"></div>
        <div class="Conflict"  data-option="id='zc_nxjc_qtx_tys>dcs01_N55116_LYPTS>DCS'" style="width:133px; display:block; top: 428px; position:absolute;color:#4cff00;text-align:right; height: 22px; left: 1373px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_W22107F01_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 457px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1376px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43111_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 483px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1375px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_T43112_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 508px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1375px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21010W01_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 536px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1376px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21011W01_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 564px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1376px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21012W01_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 588px; position: absolute; color: #4cff00; text-align: right; height: 22px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_Y21013W01_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 614px; position: absolute; color: #4cff00; text-align: right; height: 23px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_YFMH_F_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 638px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55012F01_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 666px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55013F01_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 692px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55014F01_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 719px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N55015F01_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 745px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 1374px;"></div>
        <div class="AnlogSignal mchart" id="zc_nxjc_qtx_tys>dcs01_N53302F01_LYC>DCS" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width: 132px; display: block; top: 772px; position: absolute; color: #4cff00; text-align: right; height: 25px; left: 1374px;"></div>


        <%--汉字隐藏--%>
        <%-- <div id="zc_nxjc_qtx_tys>Clinker03_DI6_131_03>DCS" class="TextDisplay" style="position:absolute; top: 183px; left: 4px; color:red;text-align:center">跑偏</div>  --%>

        <%--棒图--%>
        <%--<div class="BarGraph mchart" id="zc_nxjc_qtx_tys>Clinker03_F_43000L01>BarGraph"  style="border-style: solid; border-color: inherit; border-width: 1px; width:10px;height:75px; position:absolute; top: 547px; left: 5px;">
            <%--<div style="width:10px;margin-bottom:0px;padding-bottom:0px"></div>--%>
    </div>



    <div id="htmlContainer">
        <%--<div id="zc_nxjc_qtx_tys&gt;dcs01_SLZLJ_LB1&gt;DCS0" class="AnlogSignal mchart" data-option="Alarm='HH,H,LL,L',Range='Max,Min'" style="width:12 5px; display:block; top: 13px; left: 135px; position:absolute;color:#4cff00;text-align:right; height: 19px; bottom: 777px; right: 1298px;">
            </div>--%>
        <%--<div class="BoolSignal mchart" id="zc_nxjc_qtx_tys&gt;Clinker03_DI1_330_20&gt;BoolSignal0" style="position: absolute; top: 53px; left: 12px; height: 18px; width: 25px;" data-option="RelatedTags='Clinker03_DI1_330_20,Clinker03_DI2_330_20,,,,Clinker03_F_330_20ALM,'"></div>--%>
    </div>
</body>

</html>
